import type { LawSection } from "./law-content-114-1996";

export const HG_1386_2003_CONTENT: LawSection[] = [
  {
    type: "note",
    content: "ABROGAT - Prezenta hotărâre a fost abrogată prin intrarea în vigoare a Legii nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor.",
  },
  {
    type: "paragraph",
    content: "HOTĂRÂREA nr. 1.386 din 27 noiembrie 2003 pentru modificarea și completarea Normelor metodologice privind organizarea și funcționarea asociațiilor de proprietari, aprobate prin Hotărârea Guvernului nr. 400/2003, publicată în MONITORUL OFICIAL nr. 863 din 4 decembrie 2003.",
  },
  {
    type: "paragraph",
    content: "În temeiul art. 108 din Constituția României, republicată, și al art. 51 din Ordonanța Guvernului nr. 85/2001 privind organizarea și funcționarea asociațiilor de proprietari, aprobată cu modificări prin Legea nr. 234/2002, Guvernul României adoptă prezenta hotărâre.",
  },
  {
    type: "chapter",
    id: "cap-1",
    title: "Articol unic - Modificări și completări ale Normelor metodologice",
    children: [
      {
        type: "article",
        id: "art-1",
        title: "Punctul 1",
        content: "Articolul 4 din Normele metodologice se modifică și va avea următorul cuprins: Consiliile locale ale municipiilor, orașelor, comunelor și ale sectoarelor municipiului București vor organiza compartimente specializate pentru problemele locatarilor în scopul sprijinirii proprietarilor pentru înființarea, organizarea și funcționarea asociațiilor de proprietari și pentru realizarea scopurilor și sarcinilor ce le revin în administrarea imobilelor, în conformitate cu prevederile legale în vigoare. Aceste compartimente vor fi compuse din specialiști în domeniul financiar-contabil și al legislației muncii.",
      },
      {
        type: "article",
        id: "art-2",
        title: "Punctul 2",
        content: "Alineatele (1), (3) și (4) ale articolului 5 se modifică: (1) Condominiile pot fi administrate de persoane fizice atestate prin grija compartimentelor specializate înființate conform art. 4, angajate cu contract individual de muncă ori cu convenție civilă de prestări de servicii, sau de persoane juridice specializate; (3) Se introduce posibilitatea constituirii garanției suplimentare; (4) Garanția se depune în contul bancar al asociației.",
      },
      {
        type: "article",
        id: "art-3",
        title: "Punctul 3",
        content: "După alineatul (4) al articolului 5 se introduce alineatul (5) cu următorul cuprins: Garanția va fi constituită în maximum 6 rate lunare.",
      },
      {
        type: "article",
        id: "art-4",
        title: "Punctul 4",
        content: "Alineatul (2) al articolului 6 se modifică privind obligația comitetului executiv de a solicita un raport de gestiune la schimbarea administratorului.",
      },
      {
        type: "article",
        id: "art-5",
        title: "Punctul 5",
        content: "Alineatul (1) al articolului 8 se modifică privind constituirea asociațiilor de proprietari pe una sau mai multe scări.",
      },
      {
        type: "article",
        id: "art-6",
        title: "Punctul 6",
        content: "Articolul 9 se modifică privind decizia adunării generale cu privire la modul de exploatare a spațiilor sau elementelor aflate în proprietate comună indiviză.",
      },
      {
        type: "article",
        id: "art-7",
        title: "Punctul 7",
        content: "Articolul 12 se modifică privind obligația asociației de proprietari de a deschide cont bancar și utilizarea acestuia pentru încasări și plăți.",
      },
      {
        type: "article",
        id: "art-8",
        title: "Punctul 8",
        content: "Alineatul (3) al articolului 13 se modifică privind veniturile asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-9",
        title: "Punctul 9",
        content: "Alineatul (2) al articolului 15 se modifică privind constituirea fondului de reparații.",
      },
      {
        type: "article",
        id: "art-10",
        title: "Punctul 10",
        content: "Alineatul (2) al articolului 17 se modifică privind programul de lucrări pentru întreținerea și repararea proprietății comune.",
      },
      {
        type: "article",
        id: "art-11",
        title: "Punctul 11",
        content: "Alineatul (3) al articolului 20 se modifică privind obligația proprietarilor de a permite accesul administratorului pentru verificarea instalațiilor.",
      },
      {
        type: "article",
        id: "art-12",
        title: "Punctul 12",
        content: "Articolul 22 se modifică privind obligația administratorului de a ține evidența furnizorilor de utilități.",
      },
      {
        type: "article",
        id: "art-13",
        title: "Punctul 13",
        content: "Articolul 24 se modifică privind afișarea lunară a listei de plată a cotelor de contribuție la cheltuielile asociației.",
      },
      {
        type: "article",
        id: "art-14",
        title: "Punctul 14",
        content: "Alineatul (1) al articolului 25 se modifică: După o perioadă de 30 de zile de la termenul scadent stabilit pentru plată, asociația de proprietari poate calcula și percepe penalizări de întârziere pentru suma neachitată, în condițiile stabilite și aprobate de adunarea generală, în limitele stabilite de O.G. nr. 85/2001. Suma penalizărilor nu poate depăși suma cotei de întreținere lunare la care s-a aplicat.",
      },
      {
        type: "article",
        id: "art-15",
        title: "Punctul 15",
        content: "Alineatul (2) al articolului 35 se modifică privind veniturile obținute de asociația de proprietari din activități economice, care se constituie ca fond special utilizat exclusiv pentru îmbunătățirea confortului și eficienței condominiului.",
      },
      {
        type: "article",
        id: "art-16",
        title: "Punctul 16",
        content: "Articolul 36 se modifică privind criteriile de calcul al cheltuielilor pentru spațiile cu altă destinație decât cea de locuință.",
      },
      {
        type: "article",
        id: "art-17",
        title: "Punctul 17",
        content: "Articolul 37 se modifică privind definirea cheltuielilor pe persoană.",
      },
      {
        type: "article",
        id: "art-18",
        title: "Punctul 18",
        content: "Articolul 38 se modifică privind repartizarea cheltuielilor pe cotă-parte de proprietate.",
      },
      {
        type: "article",
        id: "art-19",
        title: "Punctul 19",
        content: "Articolul 39 se modifică privind cheltuielile cu consumul de apă rece și canalizare.",
      },
      {
        type: "article",
        id: "art-20",
        title: "Punctul 20",
        content: "Articolul 42 se modifică privind cheltuielile cu energia electrică pentru părțile comune.",
      },
      {
        type: "article",
        id: "art-21",
        title: "Punctul 21",
        content: "Articolul 43 se modifică privind cheltuielile pentru funcționarea ascensorului, cu diferențiere în funcție de etaj.",
      },
      {
        type: "article",
        id: "art-22",
        title: "Punctul 22",
        content: "Articolul 44 se modifică privind cheltuielile de colectare și transport gunoi menajer.",
      },
      {
        type: "article",
        id: "art-23",
        title: "Punctul 23",
        content: "Articolul 47 se modifică privind întocmirea listei de plată lunare.",
      },
      {
        type: "article",
        id: "art-24",
        title: "Punctul 24",
        content: "Articolul 52 se modifică privind repartizarea cheltuielilor de reparații la elementele de construcție și instalații comune.",
      },
      {
        type: "article",
        id: "art-25",
        title: "Punctul 25",
        content: "Alineatul (2) al articolului 55 se modifică privind prezentarea bilanțului anual adunării generale.",
      },
      {
        type: "article",
        id: "art-26",
        title: "Punctul 26",
        content: "Articolul 61 se modifică: În vederea evaluării persoanelor care solicită atestarea calității de administrator, consiliile locale constituie prin hotărâre comisii de atestare.",
      },
      {
        type: "article",
        id: "art-27",
        title: "Punctul 27",
        content: "Articolul 63 se modifică privind condițiile cumulative pentru atestarea ca administrator de condominii: a) capacitate deplină de exercițiu; b) garanții morale pentru îndeplinirea corectă a obligațiilor.",
      },
      {
        type: "article",
        id: "art-28",
        title: "Punctul 28",
        content: "Articolul 64 se modifică privind obligația de a urma cursuri de pregătire profesională pentru persoanele care nu au desfășurat activitate de administrare.",
      },
      {
        type: "article",
        id: "art-29",
        title: "Punctul 29",
        content: "Articolul 66 se modifică privind condițiile pentru obținerea atestatului de administrator.",
      },
      {
        type: "article",
        id: "art-30",
        title: "Punctul 30",
        content: "Articolul 67 se modifică privind depunerea cererilor de eliberare a atestatului de administrator.",
      },
      {
        type: "article",
        id: "art-31",
        title: "Punctul 31",
        content: "Articolul 68 se modifică: evaluarea se face de comisia de specialitate constituită de consiliul local, în termen de 60 de zile de la înregistrarea cererii.",
      },
      {
        type: "article",
        id: "art-32",
        title: "Punctul 32",
        content: "Articolul 71 se modifică: (1) Atestatul de administrator de imobil se eliberează pentru o perioadă nedeterminată și este valabil numai pe teritoriul administrat de autoritatea administrației publice locale emitentă; (2) Datele de identitate ale titularului; (3) Posibilitatea de suspendare sau retragere.",
      },
      {
        type: "article",
        id: "art-33",
        title: "Punctul 33",
        content: "Articolul 73 se modifică: Atestarea administratorilor persoane fizice, aflați în funcție la data intrării în vigoare a normelor metodologice, se va realiza până la data de 31 martie 2004.",
      },
      {
        type: "article",
        id: "art-34",
        title: "Punctul 34",
        content: "Articolul 74 se modifică: Consiliile locale vor stabili și vor sancționa contravențiile la prevederile normelor metodologice, prin hotărâre a consiliului local.",
      },
      {
        type: "article",
        id: "art-35",
        title: "Punctul 35",
        content: "Articolul 75 se modifică: Anexele nr. 1A, 1B și 2 fac parte integrantă din normele metodologice.",
      },
      {
        type: "article",
        id: "art-36",
        title: "Punctul 36",
        content: "După anexa nr. 1 se introduce anexa nr. 1B - Borderou cuprinzând costurile pentru încălzire și ajutoarele pentru încălzirea locuințelor racordate la rețele de gaze naturale, acordate de Guvernul României.",
      },
    ],
  },
];
