import type { LawSection } from "./law-content-114-1996";

export const LAW_230_2007_CONTENT: LawSection[] = [
  {
    type: "note",
    content: "ABROGAT: Această lege a fost abrogată prin Legea nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor, publicată în Monitorul Oficial nr. 660 din 30 iulie 2018.",
  },
  {
    type: "paragraph",
    content: "Parlamentul României adoptă prezenta lege.",
  },
  {
    type: "chapter",
    id: "cap-1",
    title: "Capitolul I - Dispoziții generale, definiții",
    children: [
      {
        type: "article",
        id: "art-1",
        title: "Articolul 1",
        content: "Prezenta lege reglementează aspectele juridice, economice și tehnice cu privire la înființarea, organizarea și funcționarea asociațiilor de proprietari, precum și modul de administrare și de exploatare a clădirilor de locuințe aflate în proprietatea a cel puțin 3 persoane fizice sau juridice, de drept public ori de drept privat, inclusiv în cazul celor care au în structura lor și spații cu altă destinație decât aceea de locuință.",
      },
      {
        type: "article",
        id: "art-2",
        title: "Articolul 2",
        content: "În condițiile art. 1, datorită stării de indiviziune forțată, proprietarii au obligația să ia măsuri cu privire la drepturile și obligațiile comune ce le revin tuturor asupra proprietății comune. În acest scop, proprietarii se pot asocia în asociații de proprietari cu personalitate juridică.",
      },
      {
        type: "article",
        id: "art-3",
        title: "Articolul 3",
        content: "În sensul prezentei legi, termenii și expresiile de mai jos au următoarele semnificații:",
        items: [
          "a) clădire-bloc de locuințe-condominiu - proprietatea imobiliară formată din proprietăți individuale, definite apartamente sau spații cu altă destinație decât aceea de locuințe, și proprietatea comună indiviză. Poate fi definit condominiu și un tronson cu una sau mai multe scări, din cadrul clădirii de locuit, în condițiile în care se poate delimita proprietatea comună;",
          "b) proprietate individuală - apartamentul sau spațiul cu altă destinație decât aceea de locuință, parte dintr-o clădire, destinată locuirii sau altor activități, care împreună cu cota-parte indiviză din proprietatea comună constituie o unitate de proprietate imobiliară. Cu excepția unor situații pentru care există alte prevederi exprese în prezenta lege sau în acordul de asociere, dreptul de proprietate asupra unei proprietăți individuale dintr-un condominiu trebuie considerat în același mod ca și dreptul de proprietate asupra altor bunuri imobile;",
          "c) proprietate comună - toate părțile dintr-un condominiu care nu sunt apartamente sau spații cu altă destinație decât aceea de locuință;",
          "d) proprietate comună aferentă tronsoanelor sau scărilor care nu poate fi delimitată - cel puțin o instalație pe verticală care alimentează în comun tronsoane ori scări sau părți de construcție comune tronsoanelor ori scărilor, care nu pot fi definite separat din punct de vedere fizic ca poziție și suprafață;",
          "e) cotă-parte indiviză - cota-parte de proprietate care îi revine fiecărei proprietăți individuale din proprietatea comună și este egală cu raportul dintre suprafața utilă a proprietății individuale și totalul suprafețelor utile ale tuturor proprietăților individuale;",
          "f) proprietar al spațiului, respectiv al apartamentului - persoana fizică sau juridică, de drept public ori de drept privat, care are în proprietate acel spațiu, respectiv apartament, într-un condominiu;",
          "g) asociație de proprietari - formă de asociere autonomă și nonprofit a majorității proprietarilor dintr-un condominiu;",
          "h) acord de asociere - actul care consfințește decizia proprietarilor de a se asocia;",
          "i) cheltuieli ale asociației de proprietari - cheltuielile sau obligațiile financiare ale asociației care sunt legate de exploatarea, reparația ori întreținerea proprietății comune, precum și cheltuielile cu serviciile de care beneficiază proprietarii și care nu sunt facturate individual către proprietățile individuale;",
          "j) cotă de contribuție la cheltuielile asociației de proprietari - suma corespunzătoare din cheltuielile asociației, pe care fiecare proprietar este obligat să o plătească lunar;",
          "k) atestat - actul care dovedește calitatea de administrator de imobil.",
        ],
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-2",
    title: "Capitolul II - Înființarea și înregistrarea asociației de proprietari",
    children: [
      {
        type: "article",
        id: "art-4",
        title: "Articolul 4",
        content: "(1) Asociația de proprietari are drept scop administrarea și gestionarea proprietății comune care, pe lângă drepturi, impune obligații pentru toți proprietarii. (2) Consecințele neluării măsurilor de organizare și funcționare cu privire la administrarea și gestiunea proprietății comune sunt în răspunderea juridică a tuturor proprietarilor sau a reprezentanților acestora, după caz.",
      },
      {
        type: "article",
        id: "art-5",
        title: "Articolul 5",
        content: "(1) Asociația de proprietari se înființează prin acordul scris a cel puțin jumătate plus unu din numărul proprietarilor apartamentelor și spațiilor cu altă destinație decât aceea de locuință, din cadrul unei clădiri. Acordul se consemnează într-un tabel nominal, anexă la acordul de asociere. (2) În clădirile de locuințe cu mai multe tronsoane sau scări se pot constitui asociații de proprietari pe fiecare tronson ori scară în parte numai în condițiile în care nu există o proprietate comună aferentă tronsoanelor sau scărilor care nu poate fi delimitată. (3) Dacă este cazul, asociațiile de proprietari înființate pe scări sau tronsoane de clădire își reglementează între ele raporturile juridice cu privire la aspectele tehnice comune acestora, printr-o anexă la acordul de asociere.",
      },
      {
        type: "article",
        id: "art-6",
        title: "Articolul 6",
        content: "(1) Cererea pentru dobândirea personalității juridice a asociației de proprietari împreună cu statutul, acordul de asociere și procesul-verbal al adunării generale de constituire se depun și se înregistrează la organul financiar local în a cărui rază teritorială se află clădirea. (2) Statutul și acordul de asociere se întocmesc în baza prezentei legi. (3) Acordul de asociere trebuie să conțină:",
        items: [
          "a) adresa și individualizarea proprietății individuale, potrivit actului de proprietate;",
          "b) numele și prenumele tuturor proprietarilor;",
          "c) descrierea proprietății, cuprinzând: descrierea clădirii, structura clădirii, numărul de etaje, numărul de apartamente structurate pe număr de camere, numărul spațiilor cu altă destinație decât aceea de locuință, suprafața terenului aferent clădirii;",
          "d) enumerarea și descrierea părților aflate în proprietate comună;",
          "e) cota-parte indiviză ce revine fiecărui proprietar din proprietatea comună.",
        ],
        children: [
          {
            type: "paragraph",
            content: "(4) Asociația de proprietari dobândește personalitate juridică în baza încheierii judecătorului-delegat desemnat la organul financiar local de către președintele judecătoriei în a cărei circumscripție teritorială se află clădirea. (5) Încheierea se dă fără citarea părților și este executorie. (6) Încheierea este supusă recursului în termen de 5 zile de la comunicare. Recursul se judecă cu citarea părților.",
          },
        ],
      },
      {
        type: "article",
        id: "art-7",
        title: "Articolul 7",
        content: "Înscrierea ulterioară în asociația de proprietari a proprietarilor care nu au fost prezenți la adunarea generală de constituire se face la cererea scrisă a acestora, fără alte formalități.",
      },
      {
        type: "article",
        id: "art-8",
        title: "Articolul 8",
        content: "(1) Pentru modificarea sau completarea statutului ori a acordului de asociere este necesar acordul a cel puțin 2/3 din numărul proprietarilor membri ai asociației de proprietari. (2) Orice modificare sau completare se înregistrează la judecătoria care a emis încheierea judecătorească de înființare, fără alte formalități.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-3",
    title: "Capitolul III - Drepturile și obligațiile proprietarilor",
    children: [
      {
        type: "article",
        id: "art-9",
        title: "Articolul 9",
        content: "Proprietarii membri ai asociației de proprietari au dreptul să participe, cu drept de vot, la adunarea generală a proprietarilor, să își înscrie candidatura, să candideze, să aleagă și să fie aleși în structura organizatorică a asociației de proprietari. Pentru a beneficia de dreptul de a fi ales, persoana în cauză trebuie să aibă capacitate deplină de exercițiu.",
      },
      {
        type: "article",
        id: "art-10",
        title: "Articolul 10",
        content: "Proprietarii au dreptul să cunoască toate aspectele ce țin de activitatea asociației și au acces, la cerere, la orice document al acesteia.",
      },
      {
        type: "article",
        id: "art-11",
        title: "Articolul 11",
        content: "(1) Proprietarul poate aduce îmbunătățiri sau modificări proprietății sale individuale, cu respectarea prevederilor legale referitoare la autorizarea de către autoritatea publică locală a modificărilor constructive, fără a pune în pericol integritatea structurală a clădirii sau a altor proprietăți individuale. (2) Proprietarul nu poate schimba aspectul sau destinația proprietății comune fără a obține mai întâi acceptul din partea asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-12",
        title: "Articolul 12",
        content: "Zidurile dintre apartamentele sau spațiile alăturate, care nu fac parte din structura de rezistență a clădirii și din proprietatea comună, pot fi reamplasate prin acordul dintre proprietarii apartamentelor sau spațiilor respective, pe baza autorizației de modificare a construcției, eliberată de autoritatea publică locală și cu înștiințarea asociației. Zidurile dintre apartamente sau spații și proprietatea comună care nu fac parte din structura de rezistență a clădirii pot fi reamplasate numai prin modificarea acordului de asociere, în baza hotărârii majorității proprietarilor și a autorizației de modificare a construcției, eliberată de autoritatea publică locală.",
      },
      {
        type: "article",
        id: "art-13",
        title: "Articolul 13",
        content: "Veniturile obținute din exploatarea proprietății comune aparțin asociației de proprietari. Aceste venituri alimentează fondurile speciale ale asociației de proprietari pentru reparații și investiții cu privire la proprietatea comună și nu se plătesc proprietarilor.",
      },
      {
        type: "article",
        id: "art-14",
        title: "Articolul 14",
        content: "Proprietarul este obligat să mențină proprietatea sa individuală, apartament sau spațiu cu altă destinație decât aceea de locuință, în stare bună, pe propria cheltuială. Niciun proprietar nu poate încălca, afecta sau prejudicia dreptul de proprietate comună sau individuală a celorlalți proprietari din condominiu.",
      },
      {
        type: "article",
        id: "art-15",
        title: "Articolul 15",
        content: "Cu un preaviz de 5 zile, proprietarul este obligat să accepte accesul în apartamentul sau în spațiul său al unui delegat al asociației, atunci când este necesar să se inspecteze, să se repare ori să se înlocuiască elemente din proprietatea comună, la care se poate avea acces numai din respectivul apartament sau spațiu. Fac excepție cazurile de urgență, când accesul se poate face fără preaviz.",
      },
      {
        type: "article",
        id: "art-16",
        title: "Articolul 16",
        content: "(1) Proprietarii sunt obligați să ia măsuri pentru consolidarea sau modernizarea clădirii, pentru reabilitarea termică și eficiența energetică, potrivit prevederilor legale. Indiferent de natura intervențiilor, se va avea în vedere menținerea aspectului armonios și unitar al întregii clădiri. (2) În clădirile afectate de seisme, proprietarii au obligația de a lua de urgență măsuri pentru consolidare, cu sprijinul autorității publice locale sau centrale.",
      },
      {
        type: "article",
        id: "art-17",
        title: "Articolul 17",
        content: "Dacă proprietarul unui apartament ori spațiu sau oricare altă persoană care acționează în numele său provoacă daune oricărei părți din proprietatea comună sau unui alt apartament ori spațiu, respectivul proprietar sau respectiva persoană are obligația să repare stricăciunile ori să plătească cheltuielile pentru lucrările de reparații.",
      },
      {
        type: "article",
        id: "art-18",
        title: "Articolul 18",
        content: "În cazurile în care în clădirile de locuințe unul dintre proprietari sau chiriași împiedică, cu bună-știință și sub orice formă, folosirea normală a clădirii de locuit, creând prejudicii celorlalți proprietari ori chiriași, după caz, proprietarii sau reprezentantul legal al acestora pot solicita instanței să hotărască măsurile pentru folosirea normală a clădirii, precum și plata daunelor.",
      },
      {
        type: "article",
        id: "art-19",
        title: "Articolul 19",
        content: "În cazul spațiilor, respectiv al apartamentelor cu mai mult de un proprietar, raporturile de coproprietate vor fi reglementate potrivit dreptului comun.",
      },
      {
        type: "article",
        id: "art-20",
        title: "Articolul 20",
        content: "(1) Proprietarii care își înstrăinează apartamentele sau spațiile cu altă destinație decât aceea de locuință sunt obligați ca la întocmirea formelor de înstrăinare să facă dovada achitării la zi a cotelor de contribuție la cheltuielile asociației de proprietari. (2) Notarii publici nu vor autentifica actele de înstrăinare fără o adeverință din partea asociației de proprietari, care să reprezinte dovada achitării la zi a cotelor de contribuție la cheltuielile asociației de proprietari, eliberată în original sub semnătura președintelui și a administratorului asociației de proprietari, cu precizarea numelui și prenumelui acestora, și cu ștampila asociației de proprietari. Actele de înstrăinare încheiate cu nerespectarea acestei obligații sunt nule de drept. (3) În cazul existenței unor datorii către asociația de proprietari, înstrăinarea proprietății se poate face numai dacă se introduce în contract o clauză privitoare la preluarea datoriilor de către cumpărător.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-4",
    title: "Capitolul IV - Organizarea și funcționarea asociației de proprietari",
    children: [
      {
        type: "article",
        id: "art-21",
        title: "Articolul 21",
        content: "(1) La adunarea generală de constituire a asociației de proprietari, proprietarii vor alege dintre cei prezenți un comitet executiv, format din președintele asociației de proprietari și un cenzor sau o comisie de cenzori, și vor hotărî numărul membrilor acestora și durata mandatelor lor. Dacă dintre membrii asociației de proprietari nu se poate alege un cenzor sau comisia de cenzori, atunci adunarea generală a proprietarilor membri ai asociației de proprietari va mandata comitetul executiv pentru angajarea unui cenzor din afara asociației de proprietari, persoană fizică ori juridică de specialitate, pe bază de contract sau convenție de prestări de servicii. (2) Cenzorul sau membrii comisiei de cenzori trebuie să aibă cel puțin studii medii și pot depune, dacă adunarea generală a asociației de proprietari hotărăște astfel, într-un cont bancar al asociației de proprietari, o garanție suficientă și îndestulătoare, pe baza unui contract de garanție încheiat în acest sens. Cuantumul garanției nu poate fi mai mic decât media anuală a totalului cheltuielilor lunare ale asociației. (3) Președintele asociației de proprietari este fie candidatul care va obține cel mai mare număr de voturi la alegerea membrilor comitetului executiv, fie oricare alt membru al comitetului executiv ales prin voința sa și a majorității proprietarilor din cadrul adunării generale. Președintele, în situații deosebite, poate numi temporar dintre membrii comitetului executiv un vicepreședinte căruia îi poate delega atribuțiile sale.",
      },
      {
        type: "article",
        id: "art-22",
        title: "Articolul 22",
        content: "(1) Deponentul garanției menționate la art. 21 alin. (2) nu poate dispune în niciun mod de suma depusă drept garanție și nici de dobânda aferentă, decât după îndeplinirea cumulativă a următoarelor condiții: aprobarea descărcării de gestiune privind exercițiul financiar precedent de către adunarea generală a membrilor asociației de proprietari, precum și încetarea efectelor delegației menționate la art. 21. (2) În cazul în care se constată de către reprezentanții asociației de proprietari sau de către proprietarii înșiși minusuri în gestiune, asociația poate dispune asupra unei sume de bani egale cu cuantumul minusului în gestiune, direct din contul bancar menționat la art. 21 alin. (2), cu aprobarea scrisă, expresă, anterioară a adunării generale, fără a avea nevoie de consimțământul deponentului garanției.",
      },
      {
        type: "article",
        id: "art-23",
        title: "Articolul 23",
        content: "(1) După adunarea generală de constituire a asociației de proprietari va avea loc cel puțin o dată pe an, în primul trimestru, o adunare generală a proprietarilor membri ai asociației. Responsabilitatea cu privire la neconvocarea a cel puțin unei adunări generale a proprietarilor aparține membrilor comitetului executiv, inclusiv președintelui asociației de proprietari. (2) Adunarea generală este alcătuită din toți proprietarii membri ai asociației de proprietari. (3) Adunarea generală ordinară se convoacă fie de președintele asociației de proprietari, fie de comitetul executiv. (4) Pentru situații speciale sau de maximă urgență, adunările generale extraordinare ale asociației pot fi convocate oricând de către comitetul executiv sau de către cel puțin 20% din numărul proprietarilor membri ai asociației de proprietari. (5) Proprietarii trebuie anunțați, prin afișare la loc vizibil sau pe bază de tabel nominal convocator, asupra oricărei adunări generale a asociației de proprietari, cu cel puțin 7 zile înainte de data stabilită, inclusiv cu privire la ordinea de zi a adunării generale. Ordinea de zi anunțată se poate completa prin hotărâre a adunării generale.",
      },
      {
        type: "article",
        id: "art-24",
        title: "Articolul 24",
        content: "(1) Adunarea generală poate adopta hotărâri, dacă majoritatea proprietarilor membri ai asociației de proprietari (jumătate plus unu) sunt prezenți personal sau prin reprezentant legal. (2) Dacă la prima convocare nu este întrunit cvorumul necesar de jumătate plus unu, adunarea generală va fi suspendată și reconvocată în termen de maximum 10 zile de la data primei convocări. (3) La adunarea generală reconvocată, dacă există dovada că toți membrii asociației de proprietari au fost convocați, hotărârile pot fi adoptate, indiferent de numărul membrilor prezenți, prin votul majorității acestora. (4) Hotărârile adunării generale a asociației de proprietari sunt obligatorii și pentru proprietarii din condominiu care nu au fost prezenți la adunarea generală, precum și pentru proprietarii care nu sunt membri ai asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-25",
        title: "Articolul 25",
        content: "(1) Pentru adoptarea hotărârilor în adunarea generală a asociației de proprietari, se vor avea în vedere următoarele:",
        items: [
          "a) fiecare proprietar are dreptul la un vot pentru proprietatea sa;",
          "b) pentru hotărârile cu privire la stabilirea fondurilor de investiții pentru consolidare, reabilitare și modernizare, votul fiecărui proprietar are o pondere egală cu cota-parte din proprietatea comună;",
          "c) proprietarul poate fi reprezentat în adunarea generală de către un membru al familiei sau de către un alt reprezentant care are o împuternicire scrisă și semnată de către proprietarul în numele căruia votează;",
          "d) un membru al asociației de proprietari poate reprezenta unul sau mai mulți membri absenți, dacă prezintă împuternicire semnată de către proprietarii în numele cărora votează;",
          "e) în cazul unui vot paritar, votul președintelui asociației de proprietari este decisiv.",
        ],
        children: [
          {
            type: "paragraph",
            content: "(2) Hotărârile adunărilor generale vor fi luate cu votul majorității membrilor asociației de proprietari prezenți la adunarea generală convocată sau reconvocată, după caz. În statutul propriu al asociației de proprietari pot fi prevăzute și alte condiții, dar nu mai puțin de jumătate plus unu din voturile celor prezenți la adunarea generală convocată sau reconvocată. (3) În situații excepționale, hotărârile pot fi luate prin acordul scris al majorității proprietarilor unei scări sau unui bloc, membri ai asociației de proprietari, pentru probleme care îi vizează direct, pe bază de tabel nominal. (4) Hotărârile adunărilor generale se consemnează în registrul de procese-verbale al asociației de proprietari, se semnează de către toți membrii comitetului executiv și se comunică, în scris, tuturor proprietarilor.",
          },
        ],
      },
      {
        type: "article",
        id: "art-26",
        title: "Articolul 26",
        content: "Dacă o hotărâre a adunării generale este contrară legii, statutului sau acordului de asociere a asociației de proprietari ori este de natură să producă daune intereselor proprietarilor, aceștia pot ataca în justiție respectiva hotărâre, în termen de 45 de zile de la adoptarea acesteia. Acționarea în justiție nu întrerupe executarea hotărârii decât în cazul în care instanța dispune suspendarea acesteia.",
      },
      {
        type: "article",
        id: "art-27",
        title: "Articolul 27",
        content: "Adunarea generală a proprietarilor membri ai asociației de proprietari are următoarele atribuții:",
        items: [
          "a) alege și revocă din funcție președintele, membrii comitetului executiv și cenzorul sau membrii comisiei de cenzori a asociației de proprietari;",
          "b) adoptă, modifică sau revocă hotărâri;",
          "c) adoptă și modifică bugetele de venituri și cheltuieli;",
          "d) mandatează comitetul executiv reprezentat de președintele asociației de proprietari pentru angajarea și eliberarea din funcție a persoanei care ocupă funcția de administrator imobile sau a altor angajați ori prestatori, în scopul administrării și bunei funcționări a clădirii;",
          "e) exercită alte atribuții care i-au fost conferite prin statut, prin acordul de asociere sau prin votul proprietarilor asociați.",
        ],
      },
      {
        type: "article",
        id: "art-28",
        title: "Articolul 28",
        content: "(1) Asociația de proprietari poate intermedia servicii între furnizori și proprietarii consumatori, în special cu privire la serviciile publice de utilități, pe baza unor contracte de prestări de servicii sau de furnizare cu caracter individual. Pentru contractele de furnizare cu caracter individual, drepturile și obligațiile cu privire la serviciul furnizat aparțin, pe de o parte, furnizorului și de cealaltă parte, proprietarului. (2) Pentru recuperarea debitelor cu privire la serviciile publice de utilități, furnizorul serviciului va acționa împotriva proprietarilor restanțieri. (3) Serviciul de intermediere din partea asociației de proprietari constă în: repartizarea facturilor către proprietari prin lista de plată lunară, încasarea și plata sumelor reprezentând contravaloarea consumului facturat, înștiințarea furnizorului cu privire la debitori.",
      },
      {
        type: "article",
        id: "art-29",
        title: "Articolul 29",
        content: "(1) Cu excepția atribuțiilor rezervate exclusiv proprietarilor cu privire la proprietățile individuale, apartamente sau spații cu altă destinație decât aceea de locuință, comitetul executiv reprezintă asociația de proprietari în administrarea și exploatarea clădirii. (2) Comitetul executiv poate angaja personal specializat pentru îndeplinirea atribuțiilor ce îi revin.",
      },
      {
        type: "article",
        id: "art-30",
        title: "Articolul 30",
        content: "(1) Comitetul executiv, reprezentat de președintele asociației de proprietari, are următoarele atribuții:",
        items: [
          "a) duce la îndeplinire hotărârile adunării generale și urmărește respectarea prevederilor legale, a statutului și a acordului de asociere ale asociației de proprietari;",
          "b) emite, dacă este cazul, decizii scrise privind reguli pentru ducerea la îndeplinire a hotărârilor adunărilor generale și pentru respectarea prevederilor legale, a statutului și a acordului de asociere, precum și alte decizii ce privesc activitatea din asociația de proprietari;",
          "c) întocmește proiectul bugetului de venituri și cheltuieli și pregătește desfășurarea adunărilor generale;",
          "d) reglementează folosirea, întreținerea, repararea, înlocuirea și modificarea părților proprietății comune, inclusiv cu privire la consumurile aferente proprietății comune;",
          "e) întocmește sau propune planuri de măsuri și activități și urmărește realizarea lor;",
          "f) supraveghează desfășurarea tuturor activităților din cadrul asociației de proprietari, în mod special situația încasărilor și plăților lunare;",
          "g) pentru scopul și activitățile asociației de proprietari, angajează și demite, încheie și reziliază contracte;",
          "h) își asumă obligații, în nume propriu sau în numele proprietarilor membri ai asociației de proprietari, privind interesele legate de clădire;",
          "i) inițiază sau apără în procese, în nume propriu sau în numele proprietarilor membri ai asociației de proprietari, interesele legate de clădire;",
          "j) stabilește sistemul propriu de penalizări ale asociației de proprietari pentru restanțele afișate pe lista de plată ce privesc cheltuielile asociației de proprietari, conform prevederilor legale;",
          "k) avizează documentele asociației de proprietari;",
          "l) asigură completarea la zi a cărții tehnice a construcției;",
          "m) asigură urmărirea comportării în timp a construcției, pe toată durata de existență a acesteia;",
          "n) gestionează situațiile excepționale și de criză;",
          "o) exercită alte atribuții care i-au fost conferite prin hotărârile adunării generale.",
        ],
        children: [
          {
            type: "paragraph",
            content: "(2) Ședințele comitetului executiv sunt legal întrunite dacă jumătate plus unu din numărul membrilor săi sunt prezenți. Ședințele comitetului executiv pot fi convocate de președintele asociației de proprietari sau de jumătate plus unu din numărul membrilor săi. (3) Deciziile comitetului executiv se consemnează în registrul de decizii al comitetului executiv.",
          },
        ],
      },
      {
        type: "article",
        id: "art-31",
        title: "Articolul 31",
        content: "(1) Președintele asociației de proprietari reprezintă asociația în derularea contractelor și își asumă obligații în numele acesteia. El reprezintă asociația de proprietari în relațiile cu terții, inclusiv în acțiunile inițiate de asociație împotriva unui proprietar care nu și-a îndeplinit obligațiile față de asociație sau în procesele inițiate de un proprietar care contestă o hotărâre a adunării generale a proprietarilor. (2) Președintele asociației de proprietari supraveghează și urmărește aplicarea hotărârilor adunării generale, respectarea prevederilor statutului și acordului de asociere, precum și aplicarea deciziilor comitetului executiv. Acesta, în funcție de situație, poate propune comitetului executiv sau adunării generale, după caz, măsuri împotriva celor care nu respectă regulile, regulamentele, hotărârile și deciziile asociației de proprietari, conform prevederilor legale și statutare.",
      },
      {
        type: "article",
        id: "art-32",
        title: "Articolul 32",
        content: "(1) Președintele asociației de proprietari sau membrii comitetului executiv pot fi remunerați pe baza unui contract de mandat, conform hotărârii adunării generale a proprietarilor, la data adoptării bugetului anual de venituri și cheltuieli. (2) Pentru neîndeplinirea atribuțiilor ce le revin, membrii comitetului executiv, inclusiv președintele asociației de proprietari, răspund personal sau în solidar, după caz, în fața legii și a proprietarilor pentru daunele și prejudiciile cauzate proprietarilor în mod deliberat.",
      },
      {
        type: "article",
        id: "art-33",
        title: "Articolul 33",
        content: "(1) Cenzorul sau comisia de cenzori a asociației de proprietari are, în principal, următoarele atribuții:",
        items: [
          "a) verifică legalitatea actelor și documentelor, a hotărârilor, deciziilor, regulilor și regulamentelor;",
          "b) verifică execuția bugetului de venituri și cheltuieli;",
          "c) verifică gestiunea financiar-contabilă;",
          "d) cel puțin o dată pe an, întocmește și prezintă adunării generale rapoarte asupra activității sale și asupra gestiunii asociației de proprietari, propunând măsuri.",
        ],
        children: [
          {
            type: "paragraph",
            content: "(2) Cenzorul sau cenzorii aleși ai asociației de proprietari pot fi remunerați pe baza unui contract de mandat, conform hotărârii adunării generale a proprietarilor, la data adoptării bugetului anual de venituri și cheltuieli. (3) Pentru neîndeplinirea atribuțiilor ce le revin, cenzorul sau cenzorii asociației de proprietari răspund personal sau în solidar, în fața legii și a proprietarilor, pentru daunele și prejudiciile cauzate proprietarilor în mod deliberat.",
          },
        ],
      },
      {
        type: "article",
        id: "art-34",
        title: "Articolul 34",
        content: "(1) Administrarea, întreținerea, investițiile și reparațiile asupra proprietății comune sunt în sarcina asociației de proprietari. (2) Asociația de proprietari angajează persoane fizice atestate pentru funcția de administrator sau încheie contracte cu persoane juridice specializate și autorizate pentru realizarea, respectiv furnizarea serviciilor necesare administrării, întreținerii, investițiilor și reparațiilor asupra proprietății comune.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-5",
    title: "Capitolul V - Administrarea în asociația de proprietari",
    children: [
      {
        type: "article",
        id: "art-35",
        title: "Articolul 35",
        content: "(1) Pentru activitatea de administrare care include activități de administrare tehnică, de contabilitate și casierie, asociația de proprietari poate angaja fie persoane fizice atestate pentru funcția de administrator de imobile, fie poate încheia contract de administrare cu persoane juridice specializate și autorizate, care au ca obiect de activitate numai domeniul asociațiilor de proprietari ori care au ca activitate principală administrarea imobilelor pe bază de tarife sau contract. Administratorilor de imobile li se aplică în mod corespunzător prevederile art. 21 alin. (2) și ale art. 22. (2) Persoanele fizice pot fi angajate prin încheierea unui contract individual de muncă, conform celor stabilite prin negociere directă. (3) Candidații pentru funcția de administrator de imobile trebuie să prezinte comitetului executiv al asociației de proprietari documentele solicitate, garanțiile profesionale și materiale prevăzute de lege și trebuie să nu fi suferit nicio condamnare. (4) Comitetul executiv adoptă decizii asupra cuantumului salariilor, al indemnizațiilor și al eventualelor premieri care se acordă personalului încadrat cu contract individual de muncă, precum și asupra valorii și a modalităților de contractare, în cazul în care administrarea clădirii este asigurată de persoane juridice, în limita bugetului de venituri și cheltuieli adoptat de adunarea generală a proprietarilor. (5) De asemenea, comitetul executiv decide și asupra acordării unor drepturi bănești membrilor asociației de proprietari care desfășoară activități lucrative folositoare acesteia, în limita bugetului de venituri și cheltuieli adoptat de adunarea generală a proprietarilor.",
      },
      {
        type: "article",
        id: "art-36",
        title: "Articolul 36",
        content: "Administratorul, persoană fizică sau juridică, are, în principal, următoarele atribuții:",
        items: [
          "a) prestarea serviciilor în mod profesional;",
          "b) gestionarea bunurilor materiale și a fondurilor bănești;",
          "c) efectuarea formalităților necesare în angajarea contractelor cu furnizorii de servicii pentru exploatarea și întreținerea clădirii, derularea și urmărirea realizării acestor contracte;",
          "d) asigurarea cunoașterii și respectării regulilor cu privire la proprietatea comună;",
          "e) gestionarea modului de îndeplinire a obligațiilor cetățenești ce revin proprietarilor în raport cu autoritățile publice. Obligațiile cetățenești sunt cele stabilite, potrivit legii, de adunarea generală a proprietarilor;",
          "f) îndeplinirea oricăror alte obligații expres prevăzute de lege.",
        ],
      },
      {
        type: "article",
        id: "art-37",
        title: "Articolul 37",
        content: "Pentru lucrările privind proprietatea comună, administratorul, ținând seama de preț, durată de execuție și calitate, supune spre analiză, selecție de oferte și aprobare comitetului executiv al asociației de proprietari ofertele operatorilor economici care satisfac cerințele, în vederea executării lucrărilor, conform legislației în vigoare.",
      },
      {
        type: "article",
        id: "art-38",
        title: "Articolul 38",
        content: "Pentru protejarea intereselor proprietarilor și ale asociației de proprietari împotriva riscurilor aferente activității de administrare într-un condominiu, administratorii de imobile, persoane fizice sau juridice, de drept public ori de drept privat, pot încheia polițe de asigurare de răspundere civilă profesională. Asigurarea de răspundere civilă profesională nu acoperă riscurile cu privire la fraudă, înșelăciune, deturnare de fonduri înfăptuite cu bună-știință. Persoanele care nu au calitatea de administrator de imobile nu pot încheia polițe de asigurare de răspundere civilă profesională.",
      },
      {
        type: "article",
        id: "art-39",
        title: "Articolul 39",
        content: "Proprietatea comună poate fi utilizată de către terți, persoane fizice sau juridice, de drept public ori de drept privat, numai cu acordul majorității proprietarilor membri ai asociației și al proprietarilor direct afectați de vecinătate, în baza unui contract de închiriere, de folosință sau de concesiune.",
      },
      {
        type: "article",
        id: "art-40",
        title: "Articolul 40",
        content: "Asociația de proprietari are obligația să ia măsuri cu privire la îmbunătățirea confortului termic al clădirii.",
      },
      {
        type: "article",
        id: "art-41",
        title: "Articolul 41",
        content: "Modificările constructive și utilizarea în alte scopuri a unor părți sau elemente de construcție ale clădirii, cum ar fi: ancorarea de reclame pe pereți, suspendarea de stâlpi, pereți, scări interioare și altele asemenea, se vor putea face numai pe baza deciziei comitetului executiv, cu acordul proprietarilor direct afectați și, după caz, pe baza unui proiect tehnic întocmit de instituții de specialitate, verificat de un expert autorizat, precum și cu autorizația pentru executarea de lucrări, eliberate în condițiile legii.",
      },
      {
        type: "article",
        id: "art-42",
        title: "Articolul 42",
        content: "Schimbarea destinației locuințelor, precum și a spațiilor cu altă destinație decât aceea de locuință față de destinația inițială, conform proiectului inițial al clădirii cu locuințe, se poate face numai cu avizul comitetului executiv și cu acceptul proprietarilor direct afectați cu care se învecinează, pe plan orizontal și vertical, spațiul supus schimbării.",
      },
      {
        type: "article",
        id: "art-43",
        title: "Articolul 43",
        content: "Pentru lucrări majore cu privire la exploatarea, întreținerea, repararea, consolidarea, reabilitarea și modernizarea proprietății comune, asociația de proprietari poate angaja, în numele proprietarilor și cu semnătura lor individuală, credite bancare sau orice alte forme de creditare, conform prevederilor legale.",
      },
      {
        type: "article",
        id: "art-44",
        title: "Articolul 44",
        content: "Pentru riscurile cu privire la proprietatea comună, asociația de proprietari, în numele proprietarilor asociați, poate încheia polițe de asigurare.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-6",
    title: "Capitolul VI - Cheltuielile asociației de proprietari",
    children: [
      {
        type: "article",
        id: "art-45",
        title: "Articolul 45",
        content: "(1) Anul fiscal al asociației de proprietari este anul calendaristic. (2) Înainte de începutul următorului an fiscal și pentru fiecare an fiscal ce urmează, comitetul executiv va pregăti și va prezenta proprietarilor în adunarea generală un buget anual de venituri și cheltuieli, suficient pentru a acoperi cheltuielile asociației de proprietari, inclusiv fondurile necesare organizării și funcționării acesteia. (3) Proprietarii membri ai asociației de proprietari au obligația să aprobe și un fond de reparații anual, necesar pentru repararea și îmbunătățirea proprietății comune. Comitetul executiv va pregăti și va prezenta adunării generale suma anuală necesară pentru constituirea sau completarea acestui fond, care se alimentează în avans, în tranșe lunare egale, prevăzute în lista de plată a cheltuielilor asociației de proprietari. Plățile pentru repararea și îmbunătățirea proprietății comune se vor face din fondul de reparații. Proprietarii membri ai asociației de proprietari pot aproba și alte fonduri cu caracter special. (4) Asociația de proprietari poate deschide unul sau mai multe conturi la oricare unitate bancară, în condițiile legii.",
      },
      {
        type: "article",
        id: "art-46",
        title: "Articolul 46",
        content: "Toți proprietarii au obligația să plătească lunar, conform listei de plată a cheltuielilor asociației de proprietari, în avans sau pe baza facturilor emise de furnizori, cota de contribuție ce le revine la cheltuielile asociației de proprietari, inclusiv cele aferente fondurilor din asociația de proprietari.",
      },
      {
        type: "article",
        id: "art-47",
        title: "Articolul 47",
        content: "Cheltuielile asociației de proprietari sunt următoarele:",
        items: [
          "a) cheltuieli pe număr de persoane care locuiesc sau desfășoară activități în proprietăți individuale;",
          "b) cheltuieli pe consumuri individuale;",
          "c) cheltuieli pe cota-parte indiviză, în funcție de suprafața utilă a proprietății individuale;",
          "d) cheltuieli pe beneficiari, aferente serviciilor individuale ale proprietarilor, dar gestionate financiar prin intermediul asociației de proprietari;",
          "e) cheltuieli pe consumatori tehnici;",
          "f) cheltuieli de altă natură.",
        ],
      },
      {
        type: "article",
        id: "art-48",
        title: "Articolul 48",
        content: "(1) Stabilirea și repartizarea sumei care privește proprietatea comună ce revine fiecărui proprietar din cadrul condominiului se fac proporțional cu cota-parte indiviză din proprietatea comună. (2) Cheltuielile efectuate de asociația de proprietari pentru plata unor servicii de utilități publice sau de altă natură, legate de proprietățile individuale din condominiu și care nu se facturează individual pe fiecare dintre acestea, se repartizează după același criteriu care a stat la baza emiterii facturii, în conformitate cu prevederile contractului încheiat cu furnizorul respectivului serviciu.",
      },
      {
        type: "article",
        id: "art-49",
        title: "Articolul 49",
        content: "(1) Asociația de proprietari poate stabili un sistem propriu de penalizări pentru orice sumă cu titlu de restanță, afișată pe lista de plată. Penalizările nu vor fi mai mari de 0,2% pentru fiecare zi de întârziere și se vor aplica numai după o perioadă de 30 de zile care depășește termenul stabilit pentru plată, fără ca suma penalizărilor să poată depăși suma la care s-au aplicat. (2) Termenul de plată a cotelor de contribuție la cheltuielile asociației de proprietari, afișate pe lista lunară de plată, este de maximum 20 de zile calendaristice. (3) Sumele rezultate din aplicarea penalităților de întârziere vor face obiectul fondului de penalități al asociației de proprietari și se vor utiliza numai pentru plata penalizărilor impuse asociației de proprietari de către terți și pentru cheltuieli cu reparațiile asupra proprietății comune sau alte cheltuieli de natură administrativă.",
      },
      {
        type: "article",
        id: "art-50",
        title: "Articolul 50",
        content: "(1) Asociația de proprietari are dreptul de a acționa în justiție pe orice proprietar care se face vinovat de neplata cotelor de contribuție la cheltuielile asociației de proprietari mai mult de 90 de zile de la termenul stabilit. (2) Acțiunea asociației de proprietari este scutită de taxă de timbru. (3) Sentința dată în favoarea asociației de proprietari, pentru sumele datorate de oricare proprietar, poate fi pusă în aplicare pentru acoperirea datoriilor prin orice modalitate permisă de Codul de procedură civilă.",
      },
      {
        type: "article",
        id: "art-51",
        title: "Articolul 51",
        content: "(1) Asociația de proprietari are un privilegiu imobiliar cu rang prioritar asupra apartamentelor și altor spații proprietăți individuale ale proprietarilor din condominiu, precum și un privilegiu asupra tuturor bunurilor mobile ale acestora, pentru sumele datorate cu titlu de cotă de contribuție la cheltuielile asociației de proprietari, după cheltuielile de judecată datorate tuturor creditorilor în interesul cărora au fost făcute. (2) Privilegiul se înscrie în registrul de publicitate imobiliară al judecătoriei, la cererea președintelui asociației de proprietari, pe baza extraselor de pe ultima listă lunară de plată a cotelor de contribuție din care rezultă suma datorată cu titlu de restanță. Privilegiul se radiază la cererea președintelui asociației de proprietari sau a proprietarului, pe baza chitanței ori a altui înscris prin care asociația confirmă plata sumei datorate. (3) Operațiunile de publicitate imobiliară privitoare la privilegiul prevăzut la alin. (1) și (2) sunt scutite de taxă de timbru.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-7",
    title: "Capitolul VII - Raportul dintre administrația publică locală și centrală și asociațiile de proprietari",
    children: [
      {
        type: "article",
        id: "art-52",
        title: "Articolul 52",
        content: "(1) Consiliile locale ale municipiilor, orașelor, comunelor și ale sectoarelor municipiului București sprijină activitatea asociațiilor de proprietari pentru realizarea scopurilor și sarcinilor ce le revin, în conformitate cu prevederile legale în vigoare. (2) Consiliile locale organizează în cadrul aparatului propriu un compartiment specializat în sprijinirea și îndrumarea asociațiilor de proprietari.",
      },
      {
        type: "article",
        id: "art-53",
        title: "Articolul 53",
        content: "(1) Compartimentele specializate înființate în cadrul autorității publice locale îndrumă și sprijină proprietarii pentru a se constitui în asociații de proprietari. (2) Consiliile locale ale municipiilor, orașelor, comunelor și ale sectoarelor municipiului București îndrumă și sprijină asociațiile de proprietari pentru îndeplinirea obligațiilor locale ce le revin asupra proprietății comune.",
      },
      {
        type: "article",
        id: "art-54",
        title: "Articolul 54",
        content: "(1) Persoanele fizice care au calitatea de administrator de imobile sunt atestate de către primar, la propunerea compartimentelor specializate din cadrul autorității administrației publice locale, în baza unei hotărâri a consiliului local. (2) Atestatul are drept scop certificarea calităților profesionale ale persoanelor care doresc să practice activitatea de administrare a imobilelor la asociațiile de proprietari.",
      },
      {
        type: "article",
        id: "art-55",
        title: "Articolul 55",
        content: "Consiliile locale, cu sprijinul aparatului propriu al consiliilor județene, respectiv al Consiliului General al Municipiului București, exercită controlul asupra activității financiar-contabile din cadrul asociațiilor de proprietari, din oficiu ori la solicitarea unuia sau mai multor membri ai asociației de proprietari.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-8",
    title: "Capitolul VIII - Sancțiuni",
    children: [
      {
        type: "article",
        id: "art-56",
        title: "Articolul 56",
        content: "(1) Constituie contravenții următoarele fapte:",
        items: [
          "a) neluarea de către proprietari, de către asociația de proprietari sau de către comitetul executiv al asociației de proprietari a tuturor măsurilor necesare pentru repararea și menținerea în stare de siguranță a clădirii și a instalațiilor comune aferente (ascensor, hidrofor, instalații de alimentare cu apă, de canalizare, de încălzire centrală, de preparare și distribuire a apei calde, instalații electrice și de gaze, centrale termice, crematorii, instalații de colectare a deșeurilor, instalații de antenă colectivă, telefonie etc.) pe toată durata existenței acestora;",
          "b) neîndeplinirea atribuțiilor de către președinte, membrii comitetului executiv, cenzori, administrator de imobil;",
          "c) neexecutarea de către proprietar a lucrărilor de întreținere, reparații sau de înlocuire a elementelor de construcții și instalații aflate în proprietatea sa individuală, dacă aceasta este de natură să aducă prejudicii celorlalți proprietari;",
          "d) schimbarea de către proprietar a destinației locuinței fără autorizațiile și aprobările legale;",
          "e) modificarea aspectului proprietății comune, precum și a elementelor constructive ale clădirii fără aprobările și autorizațiile legale;",
          "f) neaplicarea sau nerespectarea prevederilor prezentei legi de către funcționarii publici și personalul angajat al autorităților publice locale și centrale, inclusiv personalul regiilor ori al societăților furnizoare de servicii publice de utilități, dacă fapta nu a fost comisă în astfel de împrejurări încât să constituie infracțiune.",
        ],
        children: [
          {
            type: "paragraph",
            content: "(2) Contravențiile prevăzute la alin. (1) se sancționează după cum urmează: a) faptele prevăzute la lit. a), b) și c) se sancționează cu amendă de la 500 lei la 3.000 lei; b) fapta prevăzută la lit. d), cu amendă de la 200 lei la 1.000 lei; c) faptele prevăzute la lit. e) și f), cu amendă de la 2.500 lei la 5.000 lei. (3) Sancțiunile pentru contravențiile prevăzute la alin. (1) lit. a)-e) se aplică persoanelor fizice constatate vinovate, iar cea prevăzută la alin. (1) lit. f) funcționarilor publici sau personalului angajat al autorităților publice, inclusiv personalului regiilor ori societăților furnizoare de servicii de utilități publice. (4) Constatarea contravențiilor prevăzute de prezenta lege, făcută la sesizarea oricărei persoane interesate, precum și aplicarea sancțiunilor corespunzătoare se fac de către persoanele împuternicite de Inspectoratul de Stat în Construcții și de Ministerul Internelor și Reformei Administrative, de primari sau de împuterniciții acestora.",
          },
        ],
      },
      {
        type: "article",
        id: "art-57",
        title: "Articolul 57",
        content: "Prevederile art. 56 referitoare la contravenții se completează cu dispozițiile Ordonanței Guvernului nr. 2/2001 privind regimul juridic al contravențiilor, aprobată cu modificări și completări prin Legea nr. 180/2002, cu modificările și completările ulterioare.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-9",
    title: "Capitolul IX - Dispoziții tranzitorii și finale",
    children: [
      {
        type: "article",
        id: "art-58",
        title: "Articolul 58",
        content: "(1) Instituțiile administrației publice locale ori centrale sau orice alte societăți de stat, care dețin în proprietate apartamente sau spații cu altă destinație decât aceea de locuință în clădirile de locuințe, au aceleași drepturi și obligații ca oricare alt proprietar din condominiu și au obligația să mandateze persoane fizice sau juridice pentru a colabora cu asociația de proprietari. (2) Raporturile juridice ale proprietarului, stabilite de comun acord cu chiriașul, indiferent de statutul locuinței, precum și nerespectarea obligațiilor contractuale de către chiriaș nu absolvă proprietarul de la obligațiile sale față de asociația de proprietari prevăzute în prezenta lege.",
      },
      {
        type: "article",
        id: "art-59",
        title: "Articolul 59",
        content: "În termen de 60 de zile de la data intrării în vigoare a prezentei legi, Ministerul Internelor și Reformei Administrative, împreună cu Ministerul Economiei și Finanțelor, Ministerul Muncii, Familiei și Egalității de Șanse, Ministerul Transporturilor și Ministerul Justiției vor elabora și supune spre adoptare Guvernului normele metodologice de punere în aplicare a prevederilor acesteia.",
      },
      {
        type: "article",
        id: "art-60",
        title: "Articolul 60",
        content: "Prezenta lege intră în vigoare la 30 de zile de la data publicării în Monitorul Oficial al României, Partea I.",
      },
      {
        type: "article",
        id: "art-61",
        title: "Articolul 61",
        content: "La data intrării în vigoare a prezentei legi se abrogă: art. 35 alin. 3, art. 35^1, art. 36, art. 64, art. 69 și anexa nr. 2 din Legea locuinței nr. 114/1996, republicată în Monitorul Oficial al României, Partea I, nr. 393 din 31 decembrie 1997, cu modificările și completările ulterioare, Ordonanța Guvernului nr. 85/2001 privind organizarea și funcționarea asociațiilor de proprietari, publicată în Monitorul Oficial al României, Partea I, nr. 554 din 1 septembrie 2001, aprobată cu modificări prin Legea nr. 234/2002, precum și orice alte dispoziții contrare.",
      },
    ],
  },
];
