import type { LawSection } from "./law-content-114-1996";

export const NORME_2007_CONTENT: LawSection[] = [
  {
    type: "note",
    content: "ABROGAT - Aceste norme metodologice au fost abrogate prin intrarea în vigoare a noii legislații privind asociațiile de proprietari (Legea nr. 196/2018 și normele aferente).",
  },
  {
    type: "paragraph",
    content: "NORME METODOLOGICE din 19 decembrie 2007 de aplicare a Legii nr. 230/2007 privind înființarea, organizarea și funcționarea asociațiilor de proprietari.",
  },
  {
    type: "paragraph",
    content: "EMITENT: GUVERNUL. Publicat în MONITORUL OFICIAL nr. 43 din 18 ianuarie 2008.",
  },
  {
    type: "note",
    content: "Aprobate prin HOTĂRÂREA nr. 1.588 din 19 decembrie 2007, publicată în Monitorul Oficial nr. 43 din 18 ianuarie 2008.",
  },
  {
    type: "chapter",
    id: "cap-1",
    title: "Capitolul I - Dispoziții generale",
    children: [
      {
        type: "article",
        id: "art-1",
        title: "Articolul 1",
        content: "Prezentele norme metodologice au ca obiect punerea la dispoziția asociațiilor de proprietari și a autorităților administrației publice centrale și locale a cadrului general pentru înființarea, organizarea și funcționarea asociațiilor de proprietari, exploatarea și administrarea clădirilor-blocuri de locuințe-condominii, precum și exercitarea controlului financiar-contabil și de gestiune asupra activității asociațiilor de proprietari, în aplicarea prevederilor Legii nr. 230/2007 privind înființarea, organizarea și funcționarea asociațiilor de proprietari.",
      },
      {
        type: "article",
        id: "art-2",
        title: "Articolul 2",
        content: "(1) În scopul reprezentării și susținerii intereselor comune ale proprietarilor, legate de folosirea bunurilor aflate în proprietate comună indiviză din clădirea ce alcătuiește un condominiu, proprietarii apartamentelor și ai spațiilor cu altă destinație decât aceea de locuință se pot constitui în asociații de proprietari. (2) Asociația de proprietari este forma de asociere autonomă, de organizare și de reprezentare a intereselor comune a majorității proprietarilor unui condominiu, cu personalitate juridică, fără scop patrimonial, înființată în condițiile prevăzute de lege. (3) Pentru promovarea valorilor civice ale democrației și statului de drept și pentru reprezentarea la nivel local și național, asociațiile de proprietari se pot asocia în federații, uniuni, ligi ale asociațiilor de proprietari din municipii, orașe sau județe, respectiv la nivel național, în condițiile prevăzute de lege.",
      },
      {
        type: "article",
        id: "art-3",
        title: "Articolul 3",
        content: "Proprietarii din asociațiile de locatari din clădirile ale căror apartamente au fost dobândite în proprietate în condițiile legii și care nu s-au organizat în asociații de proprietari vor lua măsurile prevăzute de prezentele norme metodologice pentru constituirea în asociații de proprietari, potrivit prevederilor Legii nr. 230/2007.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-2",
    title: "Capitolul II - Înființarea, organizarea, funcționarea și administrarea asociației de proprietari",
    children: [
      {
        type: "article",
        id: "art-4",
        title: "Articolul 4",
        content: "Asociația de proprietari se înființează prin acordul scris a cel puțin jumătate plus unu din numărul proprietarilor apartamentelor și spațiilor cu altă destinație decât aceea de locuință din cadrul aceluiași condominiu cu cel puțin 3 proprietari. Acordul se consemnează într-un tabel nominal, anexă la acordul de asociere, potrivit art. 5 alin. (1) din Legea nr. 230/2007. Tabelul nominal, anexă la acordul de asociere, va conține, în mod obligatoriu, următoarele: numele și prenumele proprietarului, adresa, codul numeric personal, seria și numărul actului de identitate, indicarea titlului de proprietate, data exprimării voinței de asociere și semnătura.",
      },
      {
        type: "article",
        id: "art-5",
        title: "Articolul 5",
        content: "Cererea pentru dobândirea personalității juridice a asociației de proprietari, împreună cu statutul, acordul de asociere și procesul-verbal al adunării generale de constituire se depun și se înregistrează la organul financiar local în a cărui rază teritorială se află condominiul.",
      },
      {
        type: "article",
        id: "art-6",
        title: "Articolul 6",
        content: "Statutul asociației de proprietari trebuie să conțină: denumirea, sediul și durata de funcționare ale asociației de proprietari; scopul și obiectul de activitate; mijloacele materiale și bănești de care poate dispune asociația, precum și sursele de venituri; membrii asociației de proprietari, drepturile și obligațiile acestora; structura organizatorică și modul de funcționare; atribuțiile organelor de conducere, administrare și control; condiții de dizolvare; modul de soluționare a litigiilor.",
      },
      {
        type: "article",
        id: "art-7",
        title: "Articolul 7",
        content: "Acordul de asociere trebuie să conțină: adresa și individualizarea proprietății individuale; numele și prenumele tuturor proprietarilor; descrierea proprietății, cuprinzând: descrierea clădirii, structura clădirii, numărul de etaje, numărul de apartamente și spații cu altă destinație, suprafața terenului aferent clădirii; enumerarea și descrierea părților aflate în proprietate comună; cota-parte indiviză ce revine fiecărui proprietar din proprietatea comună.",
      },
      {
        type: "article",
        id: "art-8",
        title: "Articolul 8",
        content: "Adunarea generală a asociației de proprietari este organul de conducere al asociației, format din toți proprietarii membri ai asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-9",
        title: "Articolul 9",
        content: "Adunarea generală a asociației de proprietari adoptă hotărâri cu privire la: stabilirea cotei de contribuție a proprietarilor la cheltuielile asociației; aprobarea bugetului de venituri și cheltuieli; alegerea și revocarea membrilor comitetului executiv; alegerea și revocarea cenzorului sau comisiei de cenzori; aprobarea actelor de vânzare-cumpărare, ipotecare sau în orice alt mod de dispunere de bunurile comune; stabilirea fondurilor asociației; modificarea statutului asociației.",
      },
      {
        type: "article",
        id: "art-10",
        title: "Articolul 10",
        content: "Comitetul executiv este format din președintele asociației de proprietari și un număr par de membri, aleși dintre proprietarii din condominiu. Comitetul executiv este ales de adunarea generală a asociației de proprietari pe o perioadă stabilită prin statut.",
      },
      {
        type: "article",
        id: "art-11",
        title: "Articolul 11",
        content: "Președintele asociației de proprietari reprezintă asociația în relațiile cu terții, inclusiv în acțiunile în justiție.",
      },
      {
        type: "article",
        id: "art-12",
        title: "Articolul 12",
        content: "Cenzorul sau comisia de cenzori este aleasă de adunarea generală a asociației de proprietari și exercită controlul financiar-contabil al asociației.",
      },
      {
        type: "article",
        id: "art-13",
        title: "Articolul 13",
        content: "Administratorul este persoana fizică sau juridică, angajată sau contractată de asociația de proprietari, în baza unei hotărâri a adunării generale, cu respectarea prevederilor legale.",
      },
      {
        type: "article",
        id: "art-14",
        title: "Articolul 14",
        content: "Administratorul de imobile are obligația de a asigura managementul de proprietate al condominiului prin: gestionarea bunurilor materiale și a fondurilor bănești; efectuarea formalităților necesare în angajarea contractelor cu furnizorii de servicii; asigurarea cunoașterii și respectării regulilor de conviețuire; îndeplinirea oricăror altor obligații prevăzute de lege.",
      },
      {
        type: "article",
        id: "art-15",
        title: "Articolul 15",
        content: "Administratorul are obligația să notifice comitetului executiv orice nereguli constatate în administrarea condominiului.",
      },
      {
        type: "article",
        id: "art-16",
        title: "Articolul 16",
        content: "Asociația de proprietari, prin administrator sau prin comitetul executiv, ține evidența veniturilor și cheltuielilor, a registrelor, actelor, documentelor și a altor înscrisuri.",
      },
      {
        type: "article",
        id: "art-17",
        title: "Articolul 17",
        content: "Registrul unic al asociației de proprietari cuprinde toate actele de proprietate ale membrilor asociației, precum și contractele de închiriere.",
      },
      {
        type: "article",
        id: "art-18",
        title: "Articolul 18",
        content: "Asociația de proprietari are obligația de a ține un registru de procese-verbale al ședințelor adunărilor generale și al ședințelor comitetului executiv.",
      },
      {
        type: "article",
        id: "art-19",
        title: "Articolul 19",
        content: "Asociația de proprietari are obligația de a păstra toate documentele și evidențele contabile ale asociației, conform prevederilor legale.",
      },
      {
        type: "article",
        id: "art-20",
        title: "Articolul 20",
        content: "Fiecare proprietar are dreptul de a consulta și de a face copii de pe orice document al asociației de proprietari.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-3",
    title: "Capitolul III - Veniturile și cheltuielile asociației de proprietari",
    children: [
      {
        type: "article",
        id: "art-21",
        title: "Articolul 21",
        content: "Veniturile asociației de proprietari se constituie din: contribuțiile proprietarilor pentru cheltuielile asociației; veniturile obținute din folosirea proprietății comune; penalitățile aplicate pentru neplata la termen a contribuțiilor; alte venituri obținute în condițiile legii.",
      },
      {
        type: "article",
        id: "art-22",
        title: "Articolul 22",
        content: "Cheltuielile asociației de proprietari cuprind: cheltuielile pentru administrarea, întreținerea, repararea și, după caz, modificarea proprietăților comune; cheltuielile cu serviciile de care beneficiază proprietarii și care nu sunt facturate individual; cheltuielile cu personalul angajat sau contractat de asociație; alte cheltuieli prevăzute de lege sau stabilite de adunarea generală.",
      },
      {
        type: "article",
        id: "art-23",
        title: "Articolul 23",
        content: "Cotele de contribuție la cheltuielile asociației de proprietari se stabilesc proporțional cu cota-parte indiviză din proprietatea comună, cu consumurile utilitarilor în funcție de numărul persoanelor care locuiesc sau desfășoară activități în unitatea individuală, ori în funcție de suprafața utilă a locuinței sau a spațiului cu altă destinație.",
      },
      {
        type: "article",
        id: "art-24",
        title: "Articolul 24",
        content: "Cheltuielile asociației de proprietari se repartizează pe categorii de cheltuieli. Criteriile de repartizare se stabilesc de adunarea generală a asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-25",
        title: "Articolul 25",
        content: "Lista de plată cuprinde toate cheltuielile ce trebuie achitate de fiecare proprietar și se afișează lunar, la loc vizibil, în cadrul condominiului.",
      },
      {
        type: "article",
        id: "art-26",
        title: "Articolul 26",
        content: "Fondul de reparații se constituie prin contribuția proprietarilor în cuantumul stabilit de adunarea generală a asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-27",
        title: "Articolul 27",
        content: "Fondul de rulment se constituie prin plata anticipată a cotelor de întreținere lunare și se utilizează pentru asigurarea plății la termen a facturilor curente.",
      },
      {
        type: "article",
        id: "art-28",
        title: "Articolul 28",
        content: "Asociația de proprietari poate constitui și alte fonduri, cu aprobarea adunării generale.",
      },
      {
        type: "article",
        id: "art-29",
        title: "Articolul 29",
        content: "Administratorul are obligația de a prezenta lunar comitetului executiv și cenzorului/comisiei de cenzori situația financiară a asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-30",
        title: "Articolul 30",
        content: "Evidența contabilă a asociației de proprietari se ține în partidă simplă, conform reglementărilor legale în vigoare.",
      },
      {
        type: "article",
        id: "art-31",
        title: "Articolul 31",
        content: "Documentele justificative care stau la baza înregistrărilor în contabilitate se păstrează în conformitate cu prevederile legale.",
      },
      {
        type: "article",
        id: "art-32",
        title: "Articolul 32",
        content: "Operațiunile de încasări și plăți în numerar se fac pe baza documentelor aprobate de președintele asociației și de cenzor.",
      },
      {
        type: "article",
        id: "art-33",
        title: "Articolul 33",
        content: "Asociația de proprietari poate deschide conturi la unitățile bancare teritoriale.",
      },
      {
        type: "article",
        id: "art-34",
        title: "Articolul 34",
        content: "Bugetul de venituri și cheltuieli al asociației de proprietari se aprobă de adunarea generală și se urmărește execuția sa de către cenzor/comisia de cenzori.",
      },
      {
        type: "article",
        id: "art-35",
        title: "Articolul 35",
        content: "Cheltuielile comune privind proprietatea comună se repartizează conform cotelor-părți indivize din proprietatea comună.",
      },
      {
        type: "article",
        id: "art-36",
        title: "Articolul 36",
        content: "Cheltuielile privind consumul de apă rece și canalizare, în absența contoarelor individuale, se repartizează în funcție de numărul de persoane care locuiesc sau desfășoară activități în proprietatea individuală.",
      },
      {
        type: "article",
        id: "art-37",
        title: "Articolul 37",
        content: "Cheltuielile privind consumul de energie termică pentru încălzire se repartizează conform reglementărilor în vigoare, în funcție de suprafața utilă a locuinței sau a spațiului cu altă destinație.",
      },
      {
        type: "article",
        id: "art-38",
        title: "Articolul 38",
        content: "Cheltuielile privind consumul de energie electrică în spațiile comune se repartizează proporțional cu cota-parte indiviză din proprietatea comună.",
      },
      {
        type: "article",
        id: "art-39",
        title: "Articolul 39",
        content: "Cheltuielile privind ascensorul se repartizează în funcție de numărul de persoane care locuiesc sau desfășoară activități în proprietățile individuale situate la etajele deservite de ascensor.",
      },
      {
        type: "article",
        id: "art-40",
        title: "Articolul 40",
        content: "Cheltuielile privind salariul administratorului, contabilului și ale celorlalți angajați sau contractanți ai asociației se repartizează în funcție de numărul proprietăților individuale.",
      },
      {
        type: "article",
        id: "art-41",
        title: "Articolul 41",
        content: "Cheltuielile privind colectarea deșeurilor menajere se repartizează în funcție de numărul de persoane care locuiesc în proprietățile individuale.",
      },
      {
        type: "article",
        id: "art-42",
        title: "Articolul 42",
        content: "Cheltuielile privind curățenia și igienizarea spațiilor comune se repartizează proporțional cu cota-parte indiviză din proprietatea comună.",
      },
      {
        type: "article",
        id: "art-43",
        title: "Articolul 43",
        content: "Orice cheltuieli efectuate de asociația de proprietari trebuie justificate cu documente legale.",
      },
      {
        type: "article",
        id: "art-44",
        title: "Articolul 44",
        content: "Proprietarii sunt obligați să plătească lunar, conform listei de plată, cota de contribuție ce le revine la cheltuielile asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-45",
        title: "Articolul 45",
        content: "Pentru neplata la termen a cotelor de contribuție, proprietarii datornici sunt obligați la plata penalităților stabilite de adunarea generală a asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-46",
        title: "Articolul 46",
        content: "Asociația de proprietari poate acționa în justiție proprietarii care nu și-au achitat obligațiile financiare față de asociație mai mult de 90 de zile de la termenul stabilit.",
      },
      {
        type: "article",
        id: "art-47",
        title: "Articolul 47",
        content: "În cazul schimbării proprietarului, fostul proprietar are obligația de a transmite noului proprietar toate debitele pe care le are față de asociația de proprietari.",
      },
      {
        type: "article",
        id: "art-48",
        title: "Articolul 48",
        content: "Asociația de proprietari are obligația de a elibera, la cererea proprietarului, un certificat de atestare fiscală privind achitarea cotelor de contribuție la cheltuielile asociației.",
      },
      {
        type: "article",
        id: "art-49",
        title: "Articolul 49",
        content: "Contractele de furnizare a serviciilor necesare funcționării condominiului se încheie de asociația de proprietari, prin administrator, cu furnizorii de servicii.",
      },
      {
        type: "article",
        id: "art-50",
        title: "Articolul 50",
        content: "Asociația de proprietari are obligația de a asigura funcționarea și întreținerea corespunzătoare a instalațiilor comune ale condominiului.",
      },
      {
        type: "article",
        id: "art-51",
        title: "Articolul 51",
        content: "Proprietarii sunt obligați să permită accesul administratorului sau al delegaților asociației în proprietatea individuală atunci când este necesar pentru verificarea sau repararea instalațiilor comune.",
      },
      {
        type: "article",
        id: "art-52",
        title: "Articolul 52",
        content: "Asociația de proprietari poate contracta lucrări de întreținere, reparații curente și reparații capitale pentru proprietatea comună, cu aprobarea adunării generale.",
      },
      {
        type: "article",
        id: "art-53",
        title: "Articolul 53",
        content: "Regulile privind folosirea, întreținerea și exploatarea spațiilor și instalațiilor comune se stabilesc prin regulamentul condominiului, adoptat de adunarea generală a asociației de proprietari.",
      },
      {
        type: "article",
        id: "art-54",
        title: "Articolul 54",
        content: "Proprietarii au obligația de a respecta regulile de conviețuire stabilite prin regulamentul condominiului și prevederile legale în vigoare.",
      },
      {
        type: "article",
        id: "art-55",
        title: "Articolul 55",
        content: "Asociația de proprietari poate stabili, prin hotărârea adunării generale, sancțiuni pentru nerespectarea regulamentului condominiului.",
      },
      {
        type: "article",
        id: "art-56",
        title: "Articolul 56",
        content: "Cheltuielile privind serviciile pentru încălzirea centrală și prepararea apei calde menajere asigurate prin centrale termice proprii sau aflate în exploatarea directă a asociației de proprietari cuprind: costul combustibilului, costul transportului acestuia până la locul de consum, cheltuielile efectuate cu îndepărtarea reziduurilor, costul energiei electrice consumate pentru funcționarea instalațiilor aferente și iluminatul încăperilor în care sunt amplasate acestea, costul echipamentului de lucru și protecție pentru fochiștii care deservesc centralele termice, indemnizațiile, respectiv salariile acestora, inclusiv contribuțiile către bugetul de stat, costul materialelor necesare pentru păstrarea curățeniei în centralele termice, costul apei pentru umplerea instalației.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-4",
    title: "Capitolul IV - Raportul dintre administrația publică locală și centrală și asociațiile de proprietari",
    children: [
      {
        type: "article",
        id: "art-57",
        title: "Articolul 57",
        content: "Consiliile locale ale municipiilor, orașelor, comunelor și ale sectoarelor municipiului București organizează compartimente specializate în scopul sprijinirii proprietarilor pentru înființarea, organizarea și funcționarea asociațiilor de proprietari și pentru realizarea scopurilor și sarcinilor ce le revin în administrarea imobilelor, în conformitate cu prevederile legale în vigoare. Compartimentele specializate înființate în cadrul autorităților administrației publice locale au în componență specialiști în domeniul financiar-contabil, tehnic, juridic, al legislației muncii și a raporturilor de muncă.",
      },
      {
        type: "article",
        id: "art-58",
        title: "Articolul 58",
        content: "(1) Persoanele fizice care doresc să obțină calitatea de administrator de imobile sunt atestate de către primar, la propunerea compartimentelor specializate din cadrul autorității administrației publice locale, în baza unei hotărâri a consiliului local. (2) Atestatul are drept scop certificarea calităților profesionale ale persoanelor care doresc să practice activitatea de administrare a imobilelor la asociațiile de proprietari. (3) Atestatul de administrator de imobil se eliberează pentru o perioadă nedeterminată și este valabil pe tot teritoriul României. (4) Atestatul de administrator de imobil se poate retrage de către autoritatea administrației publice locale care l-a eliberat, dacă nu mai sunt îndeplinite condițiile pentru exercitarea acestei activități.",
      },
      {
        type: "article",
        id: "art-59",
        title: "Articolul 59",
        content: "(1) Exercitarea controlului asupra activității financiar-contabile din cadrul asociațiilor de proprietari se realizează în conformitate cu prevederile art. 55 din Legea nr. 230/2007 de către organele competente potrivit legislației financiar-contabile. (2) Asociația de proprietari sau orice proprietar din condominiu poate contracta, în nume propriu, lucrări de expertiză tehnică și/sau contabilă cu o persoană fizică sau juridică care are calitatea de a efectua expertize, conform legislației privind organizarea activității de expertiză tehnică și contabilă, judiciară și extrajudiciară. (3) În condițiile stabilite de consiliile locale, județene sau de Consiliul General al Municipiului București și în funcție de resursele bugetare proprii, primăriile pot încheia parteneriate cu Corpul Experților Contabili și Contabililor Autorizați din România, în vederea efectuării expertizei financiar-contabile a gestiunii fondurilor asociațiilor de proprietari, la solicitarea unuia sau a mai multor membri ai asociației, ulterior efectuării de către comisia de cenzori a controlului financiar-contabil pe respectiva perioadă.",
      },
    ],
  },
  {
    type: "chapter",
    id: "cap-5",
    title: "Capitolul V - Dispoziții tranzitorii și finale",
    children: [
      {
        type: "article",
        id: "art-60",
        title: "Articolul 60",
        content: "Până la elaborarea și aprobarea normelor privind repartizarea consumurilor de energie termică pentru încălzire și apă caldă menajeră, în cazul utilizării repartitoarelor de costuri, se aplică metodologiile însușite și aprobate de asociațiile de proprietari.",
      },
      {
        type: "article",
        id: "art-61",
        title: "Articolul 61",
        content: "Prezentele norme metodologice intră în vigoare la 3 zile de la data publicării în Monitorul Oficial al României, Partea I.",
      },
    ],
  },
];
