import type { LawSection } from "./law-content-114-1996";

export const ORDIN_1058_2019_CONTENT: LawSection[] = [
  {
    type: "paragraph",
    content: "ORDIN nr. 1.058 din 11 februarie 2019 privind aprobarea conținutului-cadru al statutului asociației de proprietari și al regulamentului condominiului",
  },
  {
    type: "paragraph",
    content: "EMITENT: MINISTERUL DEZVOLTĂRII REGIONALE ȘI ADMINISTRAȚIEI PUBLICE. Publicat în MONITORUL OFICIAL nr. 149 din 25 februarie 2019.",
  },
  {
    type: "paragraph",
    content: "Având în vedere prevederile art. 108 alin. (2) din Legea nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor, în conformitate cu prevederile art. 1 din Ordonanța de urgență a Guvernului nr. 1/2018 pentru aprobarea unor măsuri de reorganizare în cadrul administrației publice centrale și pentru modificarea unor acte normative, aprobată prin Legea nr. 147/2018, în temeiul art. 12 alin. (6) din Hotărârea Guvernului nr. 51/2018 privind organizarea și funcționarea Ministerului Dezvoltării Regionale și Administrației Publice, cu modificările ulterioare, viceprim-ministrul, ministrul dezvoltării regionale și administrației publice, emite următorul ordin:",
  },
  {
    type: "article",
    id: "art-1",
    title: "Articolul 1",
    content: "Se aprobă conținutul-cadru al statutului asociației de proprietari, prevăzut în anexa nr. 1, care face parte integrantă din prezentul ordin.",
  },
  {
    type: "article",
    id: "art-2",
    title: "Articolul 2",
    content: "Se aprobă conținutul-cadru al regulamentului condominiului, prevăzut în anexa nr. 2, care face parte integrantă din prezentul ordin.",
  },
  {
    type: "article",
    id: "art-3",
    title: "Articolul 3",
    content: "Prezentul ordin intră în vigoare în termen de 3 de zile de la data publicării în Monitorul Oficial al României, Partea I.",
  },
  {
    type: "paragraph",
    content: "p. Viceprim-ministru, ministrul dezvoltării regionale și administrației publice, interimar, Adrian Ionuț Gâdea, secretar de stat. București, 11 februarie 2019. Nr. 1.058.",
  },
  {
    type: "annexa",
    id: "anexa-1",
    title: "Anexa nr. 1 - CONȚINUT-CADRU al statutului asociației de proprietari",
    children: [
      {
        type: "paragraph",
        content: "Aprobat prin Ordinul nr. 1.058 din 11 februarie 2019, publicat în Monitorul Oficial, Partea I, nr. 149 din 25 februarie 2019.",
      },
      {
        type: "chapter",
        id: "anexa1-cap-1",
        title: "Capitolul I - Dispoziții generale",
        children: [
          {
            type: "article",
            id: "anexa1-art-1",
            title: "Articolul 1",
            content: "Prezentul statut al asociației de proprietari, denumit în continuare statut, reprezintă ansamblul dispozițiilor, adoptat de cel puțin jumătate plus unu din numărul proprietarilor din condominiu, prin care se reglementează scopul, structura și modul de organizare și funcționare a asociației de proprietari, cu respectarea prevederilor Legii nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor.",
          },
          {
            type: "article",
            id: "anexa1-art-2",
            title: "Articolul 2",
            content: "Dispozițiile prezentului statut se completează cu dispozițiile Legii nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-3",
            title: "Articolul 3",
            content: "Dispozițiile prezentului statut sunt adoptate în conformitate cu prevederile legislației în vigoare și nu derogă de la acestea.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-2",
        title: "Capitolul II - Denumire, sediul, durata de funcționare a asociației de proprietari",
        children: [
          {
            type: "article",
            id: "anexa1-art-4",
            title: "Articolul 4",
            content: "Asociația de proprietari .................................... (denumire), cu sediul în ........................................ (adresă), denumită în continuare asociația de proprietari, se constituie/reorganizează în condițiile Legii nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor, în vederea funcționării pe durată nedeterminată, pentru îndeplinirea atribuțiilor prevăzute de lege.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-3",
        title: "Capitolul III - Scopul asociației de proprietari",
        children: [
          {
            type: "article",
            id: "anexa1-art-5",
            title: "Articolul 5",
            content: "Asociația de proprietari se constituie în scopul exercitării drepturilor și obligațiilor legale ce le revin proprietarilor din condominiu asupra proprietății comune.",
          },
          {
            type: "article",
            id: "anexa1-art-6",
            title: "Articolul 6",
            content: "Asociația de proprietari este forma juridică de organizare și de reprezentare a intereselor comune ale proprietarilor din condominiu, cu personalitate juridică, fără scop lucrativ, apolitică și fără scop patrimonial, înființată în condițiile legii, care are ca scop administrarea, exploatarea, întreținerea, repararea, reabilitarea și modernizarea proprietății comune, menținerea în stare bună a imobilului, respectarea drepturilor și asumarea obligațiilor de către toți proprietarii.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-4",
        title: "Capitolul IV - Structura veniturilor și a cheltuielilor asociației de proprietari",
        children: [
          {
            type: "article",
            id: "anexa1-art-7",
            title: "Articolul 7",
            content: "(1) Toate veniturile obținute din exploatarea proprietății comune, precum amplasarea mijloacelor de publicitate, amplasarea de antene, închirierea spațiilor comune și altele asemenea, inclusiv veniturile din dobânzi bancare, aparțin asociației de proprietari, alimentează numai fondul de reparații al asociației de proprietari și nu se plătesc proprietarilor. (2) Lista acestor venituri, precum și cheltuielile aferente lor sunt prezentate semestrial, într-un raport afișat la avizierul asociației și se evidențiază în registrul unic de venituri și cheltuieli al asociației de proprietari, conform Legii nr. 196/2018. (3) Administratorul este obligat să folosească pentru plățile curente și pentru încasări contul curent al asociației de proprietari, la care au acces pentru informare, conform prevederilor art. 67 din Legea nr. 196/2018, toți proprietarii din condominiu. (4) Prin grija președintelui, proprietarii din condominiu au acces la extrasele de cont, emise automat conform contractului de cont curent al asociației de proprietari. (5) În cazul în care unul sau mai mulți proprietari solicită accesul la extrase de cont, altele decât cele prevăzute la alin. (4), aceștia vor suporta costul emiterii extraselor de cont, conform contractului de cont curent.",
          },
          {
            type: "article",
            id: "anexa1-art-8",
            title: "Articolul 8",
            content: "Fondurile asociației de proprietari sunt:",
            items: [
              "a) fondul de reparații;",
              "b) fondul de rulment;",
              "c) fondul de penalități;",
              "d) fondul ...................................  (alte fonduri aprobate în cadrul adunării generale).",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-9",
            title: "Articolul 9",
            content: "(1) Proprietarii membri ai asociației de proprietari aprobă un fond de reparații anual, necesar pentru repararea și îmbunătățirea proprietății comune, conform art. 71 din Legea nr. 196/2018. (2) Sumele încasate pentru constituirea fondului de reparații se depun în contul bancar unic al asociației de proprietari, conform Legii nr. 196/2018. (3) Pentru încasarea fondului de reparații, administratorul eliberează chitanță nominală separată.",
          },
          {
            type: "article",
            id: "anexa1-art-10",
            title: "Articolul 10",
            content: "(1) Asociația de proprietari este obligată să stabilească cuantumul și cota de participare a proprietarilor la constituirea fondului de rulment, conform art. 72 din Legea nr. 196/2018. (2) Fondul de rulment se depune în contul bancar unic al asociației de proprietari, conform Legii nr. 196/2018. (3) Pentru încasarea fondului de rulment, administratorul eliberează chitanță nominală separată. (4) Fondul de rulment încasat se restituie la transmiterea dreptului de proprietate, dacă prin actele translative de proprietate nu se stipulează altfel.",
          },
          {
            type: "article",
            id: "anexa1-art-11",
            title: "Articolul 11",
            content: "(1) În cadrul adunării generale, proprietarii membri ai asociației de proprietari pot aproba și alte fonduri cu caracter special, precum și modul de constituire al acestora. Constituirea fondurilor cu caracter special nu este obligatorie. (2) Fondurile cu caracter special aprobate în cadrul adunării generale, cu respectarea prevederilor art. 48 din Legea nr. 196/2018, sunt prevăzute, împreună cu fondul de reparații, fondul de rulment și fondul de penalități, la art. 8 din prezentul statut. (3) Toate fondurile speciale ale asociației de proprietari se depun în contul bancar unic al asociației de proprietari, conform Legii nr. 196/2018, au evidență separată și pentru fiecare fond se emite chitanță separată.",
          },
          {
            type: "article",
            id: "anexa1-art-12",
            title: "Articolul 12",
            content: "(1) Cheltuielile asociației de proprietari sunt cheltuieli legate de exploatarea, repararea sau întreținerea proprietății comune și cheltuielile pentru asigurarea serviciilor de care beneficiază proprietarii și care nu sunt facturate individual către proprietățile individuale. (2) Cheltuielile asociațiilor de proprietari, în funcție de modul de calcul și de criteriile de repartizare pe proprietăți individuale, așa cum sunt prevăzute la art. 75 din Legea nr. 196/2018, sunt următoarele:",
            items: [
              "a) cheltuieli pe număr de persoane care locuiesc sau desfășoară activități în proprietăți individuale;",
              "b) cheltuieli pe consumuri individuale;",
              "c) cheltuieli pe cota-parte indiviză, în funcție de suprafața utilă a proprietății individuale;",
              "d) cheltuieli pe beneficiari, aferente serviciilor individuale ale proprietarilor, dar gestionate financiar prin intermediul asociației de proprietari;",
              "e) cheltuieli pe consumatori tehnici;",
              "f) cheltuieli de altă natură.",
            ],
            children: [
              {
                type: "paragraph",
                content: "(3) Asociația de proprietari are obligația de a respecta prevederile legale privind modul de repartizare a cheltuielilor comune, în caz contrar, hotărârile luate de adunarea generală a proprietarilor cu încălcarea acestor dispoziții sunt nule de drept. (4) Niciun proprietar din condominiu nu este exceptat de la obligația de a contribui la plata cheltuielilor comune, ca urmare a renunțării la folosirea unei părți din proprietatea comună. (5) Prin excepție de la prevederile alin. (4), în baza hotărârii adunării generale, pot fi exceptate de la plata cheltuielilor aferente consumului de energie electrică pentru funcționarea ascensorului/ascensoarelor persoanele care locuiesc în apartamente situate la subsol, demisol, parter, mezanin, precum și la etajul 1 din clădirile fără mezanin.",
              },
            ],
          },
          {
            type: "article",
            id: "anexa1-art-13",
            title: "Articolul 13",
            content: "(1) Asociația de proprietari poate stabili un sistem propriu de penalități pentru orice sumă cu titlu de restanță, afișată pe lista de plată. Penalitățile nu vor fi mai mari de 0,2% pentru fiecare zi de întârziere și se vor aplica numai după o perioadă de 30 de zile de la termenul scadent pentru plată, fără ca suma penalităților să poată depăși suma la care s-au aplicat. (2) În baza Hotărârii Adunării generale, cuantumul penalităților de întârziere pentru sumele cu titlu de restanță, afișată pe lista de plată, este stabilit conform legii. (3) Termenul de plată a cotelor de contribuție la cheltuielile asociației de proprietari, afișate pe lista lunară de plată, este de maximum 30 de zile calendaristice de la data afișării. (4) Sumele rezultate din aplicarea penalităților de întârziere se includ în fondul de penalități al asociației de proprietari și se vor utiliza cu prioritate pentru plata penalităților impuse asociației de proprietari de către terți, precum și pentru cheltuieli cu reparațiile asupra proprietății comune, reabilitarea termică sau consolidarea condominiului. Sumele rezultate din aplicarea penalităților de întârziere nu pot fi utilizate și în alte scopuri.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-5",
        title: "Capitolul V - Membrii asociației de proprietari, precum și drepturile și obligațiile acestora",
        children: [
          {
            type: "article",
            id: "anexa1-art-14",
            title: "Articolul 14",
            content: "(1) Prin membru al asociației de proprietari se înțelege proprietarul locuinței sau spațiului cu altă destinație decât aceea de locuință din condominiu, semnatar al acordului de asociere sau al unei cereri depuse la asociație, în condițiile Legii nr. 196/2018. (2) Prin proprietar se înțelege persoana fizică sau juridică, titular al unui drept de proprietate asupra a cel puțin o unitate de proprietate imobiliară dintr-un condominiu. (3) În cazul unităților de proprietate imobiliară cu mai mult de un proprietar, raporturile de coproprietate dintre aceștia sunt reglementate potrivit dreptului comun. Indiferent de numărul proprietarilor unei unități de proprietate imobiliară, aceștia au dreptul la un singur vot pentru unitatea de proprietate imobiliară în cadrul adunării generale a asociației de proprietari. (4) Odată cu pierderea calității de proprietar în condominiu încetează statutul de membru al respectivei asociații de proprietari.",
          },
          {
            type: "article",
            id: "anexa1-art-15",
            title: "Articolul 15",
            content: "Toți proprietarii membri ai asociației de proprietari au dreptul să participe, cu drept de vot, la adunarea generală a asociației de proprietari, să își înscrie candidatura, să candideze, să aleagă și să fie aleși în structura organizatorică a asociației de proprietari, potrivit Legii nr. 196/2018. Pentru a beneficia de dreptul de a fi ales, persoana în cauză trebuie să aibă capacitate deplină de exercițiu.",
          },
          {
            type: "article",
            id: "anexa1-art-16",
            title: "Articolul 16",
            content: "(1) Proprietarii din condominiu au dreptul să fie informați în legătură cu toate aspectele ce privesc activitatea asociației, să solicite în scris și să primească copii după orice document al acesteia. Proprietarii care solicită copii după documentele asociației de proprietari vor suporta costul de multiplicare al acestora. (2) Proprietarii din condominii au dreptul să primească explicații cu privire la calculul cotei de contribuție la cheltuielile asociației de proprietari și, după caz, să o conteste în scris, în termen de 10 zile de la afișarea listei de plată. Președintele asociației de proprietari este obligat să răspundă, în scris, la contestație în termen de 10 zile de la primirea acesteia.",
          },
          {
            type: "article",
            id: "anexa1-art-17",
            title: "Articolul 17",
            content: "(1) Proprietarii din condominii au obligația, conform prevederilor art. 30 din Legea nr. 196/2018, să notifice președintelui orice schimbare intervenită, respectiv schimbări în structura și numărul membrilor familiei prin deces, căsătorii sau nașteri, persoanele luate în spațiu, precum și locatarii/comodatarii ca urmare a închirierii sau a împrumutării locuinței. (2) În condițiile Legii nr. 196/2018 și cu respectarea prevederilor legislației în vigoare privind calitatea în construcții, proprietarul este obligat să mențină proprietatea sa individuală, locuință sau spațiu cu altă destinație decât aceea de locuință, în stare bună din punct de vedere tehnic și funcțional, pe propria cheltuială. Niciun proprietar, chiriaș sau angajat al asociației de proprietari nu poate încălca, afecta sau prejudicia dreptul de proprietate comună sau individuală a celorlalți proprietari din condominiu și nu poate afecta funcționarea normală și întreținerea condominiului. (3) În cadrul proprietății individuale, proprietarul are obligația să păstreze și să întrețină în stare de funcționare și siguranță spațiile interioare, echipamentele și instalațiile din dotarea tehnică a proprietății individuale, respectiv instalațiile sanitare, de încălzire, canalizare, alimentare cu energie electrică, gaz, apă, precum și altele de această natură, pe cheltuiala sa, astfel încât să nu aducă prejudicii celorlalți proprietari din condominiu. (4) Dacă proprietarul unei locuințe ori al unui spațiu cu altă destinație provoacă daune oricărei părți din proprietatea comună sau din proprietatea individuală a altui proprietar din condominiu, respectivul proprietar are obligația să repare stricăciunile sau să suporte cheltuielile pentru lucrările de reparații. (5) Raporturile juridice stabilite de comun acord între locator și locatar, precum și nerespectarea obligațiilor contractuale de către locatar nu absolvă proprietarul, în calitate de locator, de obligațiile sale față de asociația de proprietari sau față de furnizorii de utilități publice, prevăzute în Legea nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-18",
            title: "Articolul 18",
            content: "(1) Proprietarii sunt obligați să ia măsuri pentru consolidarea și modernizarea condominiului, modernizarea echipamentelor, instalațiilor și dotărilor aferente, montarea contoarelor pentru individualizarea consumurilor la nivel de proprietate individuală, reabilitarea termică în scopul creșterii performanței energetice, precum și reabilitarea structural-arhitecturală a anvelopei condominiului pentru creșterea calității arhitectural-ambientale a acestuia, potrivit prevederilor legale, în condițiile menținerii aspectului armonios și unitar al întregului condominiu, indiferent de natura intervențiilor. (2) În cazul condominiilor de tipul imobilelor colective multietajate, modificarea aspectului fațadei se face numai în mod unitar pe întreg condominiul, indiferent de numărul asociațiilor de proprietari constituite pe scări sau tronsoane, în baza unei documentații tehnice elaborate în condițiile legii, cu respectarea prevederilor art. 32 alin. (2) din Legea nr. 196/2018. (3) Înainte de modificarea aspectului fațadei condominiului, președintele asociației de proprietari solicită, în scris, autorității administrației publice locale toate informațiile și restricțiile referitoare la culoare, aspect, materiale și altele asemenea, stabilite conform legislației în vigoare, cu respectarea prevederilor art. 32 alin. (3) din Legea nr. 196/2018. (4) În cazul condominiilor cu mai multe tronsoane sau scări legate structural, lucrările de consolidare sau modernizare, reabilitare termică și structural-arhitecturală se vor realiza în mod unitar pentru întregul ansamblu, cu respectarea întocmai a caracterului arhitectural al condominiului și al caracterului ambiental al ansamblului/zonei de amplasament în baza unei documentații tehnice elaborate în condițiile legii și cu respectarea prevederilor legale în vigoare privind autorizarea executării lucrărilor de construcții, regimul monumentelor istorice și al zonelor protejate, după caz. (5) Proprietarii construcțiilor, persoane fizice sau juridice, și asociațiile de proprietari, precum și persoanele juridice care au în administrare construcții încadrate în clasele de risc seismic și/sau afectate de seisme sunt obligați să ia măsurile prevăzute de lege pentru reducerea riscului seismic al construcțiilor.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-6",
        title: "Capitolul VI - Structura organizatorică și modul de funcționare",
        children: [
          {
            type: "article",
            id: "anexa1-art-19",
            title: "Articolul 19",
            content: "Organele asociației de proprietari sunt:",
            items: [
              "a) adunarea generală;",
              "b) comitetul executiv;",
              "c) președintele;",
              "d) cenzorul sau comisia de cenzori.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-20",
            title: "Articolul 20",
            content: "Funcția de președinte, respectiv membru în comitetul executiv este incompatibilă cu funcția de cenzor sau membru în comisia de cenzori.",
          },
          {
            type: "article",
            id: "anexa1-art-21",
            title: "Articolul 21",
            content: "(1) Adunarea generală este alcătuită din toți proprietarii membri ai asociației de proprietari. (2) Adunarea generală ordinară se convoacă de către:",
            items: [
              "a) președintele asociației de proprietari sau comitetul executiv;",
              "b) cel puțin 20% din numărul proprietarilor membri ai asociației de proprietari.",
            ],
            children: [
              {
                type: "paragraph",
                content: "(3) Pentru adoptarea hotărârilor în adunarea generală a asociației de proprietari se au în vedere următoarele: a) fiecare proprietar, membru al asociației, are dreptul la un vot pentru unitatea sa de proprietate imobiliară; b) pentru hotărârile cu privire la stabilirea fondurilor pentru consolidare, reabilitare și modernizare, votul fiecărui proprietar, membru al asociației, are o pondere egală cu cota-parte indiviză din proprietatea comună; c) în situația în care un proprietar deține o cotă-parte indiviză de părți comune mai mare de jumătate din totalul cotelor-părți indivize de proprietate comună din condominiu, ponderea voturilor de care el dispune este limitată, fiind egală cu suma ponderii voturilor celorlalți proprietari; d) proprietarul, membru al asociației, poate fi reprezentat în adunarea generală de către un membru al familiei sau de către un alt reprezentant care are o împuternicire scrisă și semnată de către proprietarul în numele căruia votează; e) un membru al asociației de proprietari poate reprezenta cel mult un membru absent, dacă prezintă împuternicire scrisă și semnată de către proprietarii în numele cărora votează; f) președintele, membrii comitetului executiv, administratorul, cenzorul/comisia de cenzori sau alt membru al familiilor acestora nu pot primi mandat pentru a reprezenta un alt proprietar în cadrul adunării generale; g) în cazul unui vot paritar, votul președintelui asociației de proprietari este decisiv; h) administratorul, reprezentantul administratorului, soțul/soția acestuia și alți membri ai familiei sale, dacă sunt membri ai asociației de proprietari la care acesta este angajat, nu au drept de vot în probleme referitoare la activitatea administratorului.",
              },
              {
                type: "paragraph",
                content: "(4) Acordul de voință al asociației de proprietari se realizează în adunarea generală a asociației de proprietari. În cazurile excepționale, atunci când sunt necesare adoptarea unor hotărâri în regim de urgență sau atunci când, după convocarea adunării generale a asociației de proprietari, conform art. 48 din Legea nr. 196/2018, nu a fost întrunit numărul membrilor prezenți pentru adoptarea hotărârilor, conform prevederilor legale, acordul de voință al asociației de proprietari se poate realiza și în baza declarațiilor scrise și semnate ale fiecărui proprietar. (5) Declarațiile menționate la alin. (4) sunt redactate astfel încât să reiasă în mod clar și fără echivoc acordul sau dezacordul proprietarului din condominiu față de propunerea de hotărâre a adunării generale a asociației de proprietari.",
              },
            ],
          },
          {
            type: "article",
            id: "anexa1-art-22",
            title: "Articolul 22",
            content: "Adunarea generală a proprietarilor membri ai asociației de proprietari are următoarele atribuții:",
            items: [
              "a) alege și revocă din funcție președintele, ceilalți membri ai comitetului executiv și cenzorul/comisia de cenzori;",
              "b) adoptă și modifică statutul și regulamentul condominiului;",
              "c) adoptă, modifică sau revocă hotărâri;",
              "d) adoptă și modifică bugetul de venituri și cheltuieli;",
              "e) adoptă hotărâri privind executarea lucrărilor de întreținere, reparații, modernizare, consolidare și reabilitare termică și eficiență energetică a condominiului;",
              "f) în baza acordului scris al tuturor proprietarilor, adoptă hotărâri privind contractarea de împrumuturi de la bănci în vederea acoperirii cheltuielilor pentru consolidarea și modernizarea condominiului, modernizarea instalațiilor și dotărilor aferente, reabilitarea termică în scopul creșterii performanței energetice, precum și pentru reabilitarea structural-arhitecturală a anvelopei în vederea creșterii calității ambiental-arhitecturale a condominiului, potrivit prevederilor legale;",
              "g) adoptă hotărâri asupra fondului anual de salarii și indemnizații;",
              "h) adoptă hotărâri asupra cuantumului indemnizațiilor, precum și asupra numărului și funcțiilor personalului încadrat cu contract individual de muncă sau contract de prestări servicii în cadrul asociației de proprietari pentru buna administrare, gestionare și funcționare a condominiului, dar și asupra valorii și a modalităților de contractare, în limita bugetului de venituri și cheltuieli;",
              "i) stabilește modalitățile și tranșele de plată a contribuțiilor fiecărui proprietar, pentru fiecare dintre categoriile de cheltuieli, conform reglementărilor în vigoare;",
              "j) stabilește sistemul de penalizări pentru restanțele afișate pe lista de plată ce privesc cheltuielile asociației de proprietari, conform prevederilor legale în vigoare;",
              "k) mandatează președintele și comitetul executiv pentru angajarea și eliberarea din funcție a administratorului, cenzorului/comisiei de cenzori sau a altor angajați ori prestatori, în scopul administrării și bunei funcționări a condominiului;",
              "l) poate stabili plafoanele minime de la care achiziționarea bunurilor sau contractarea serviciilor se face pe baza ofertelor operatorilor economici care satisfac cerințele asociației de proprietari, conform legislației în vigoare;",
              "m) exercită alte atribuții care i-au fost conferite prin statut, prin acordul de asociere sau prin votul proprietarilor membri ai asociației.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-23",
            title: "Articolul 23",
            content: "(1) Membrii comitetului executiv sunt desemnați de către adunarea generală a asociației de proprietari, dintre membrii asociației de proprietari. (2) Comitetul executiv este format din președintele asociației și un număr par de membri, nu mai mare de patru, astfel încât numărul membrilor comitetului executiv nu poate fi mai mare de cinci.",
          },
          {
            type: "article",
            id: "anexa1-art-24",
            title: "Articolul 24",
            content: "(1) Comitetul executiv are următoarele atribuții:",
            items: [
              "a) convoacă adunarea generală a asociației de proprietari cel puțin o dată pe an și ori de câte ori este necesar;",
              "b) duce la îndeplinire hotărârile adunării generale și urmărește respectarea prevederilor legale, a statutului, a acordului de asociere și a regulamentului condominiului;",
              "c) emite, dacă este cazul, decizii scrise privind reguli pentru ducerea la îndeplinire a hotărârilor adunării generale și pentru respectarea prevederilor legale, a statutului și a acordului de asociere, precum și alte decizii ce privesc activitatea asociației de proprietari;",
              "d) propune spre adoptare adunării generale proiectul de regulament al condominiului, cu respectarea dispozițiilor Legii nr. 196/2018;",
              "e) întocmește proiectul bugetului de venituri și cheltuieli și pregătește desfășurarea adunărilor generale;",
              "f) stabilește condițiile privind folosirea, întreținerea, repararea, înlocuirea și modificarea părților proprietății comune, conform prevederilor legale în vigoare;",
              "g) ia măsuri pentru recalcularea cotelor-părți indivize rezultate în urma modificării suprafețelor utile ale locuințelor sau spațiilor cu altă destinație din condominiu;",
              "h) întocmește și propune adunării generale planuri de măsuri și activități și urmărește realizarea lor;",
              "i) supraveghează desfășurarea tuturor activităților din cadrul asociației de proprietari, inclusiv situația încasărilor și plăților lunare;",
              "j) stabilește programul de încasări al asociației de proprietari;",
              "k) își asumă obligații, în baza hotărârii adunării generale, în numele proprietarilor membri ai asociației de proprietari, în ceea ce privește administrarea condominiului, luând toate măsurile legale necesare;",
              "l) este consultat în legătură cu toate activitățile care implică asociația de proprietari;",
              "m) asigură urmărirea comportării în timp a construcției, pe toată durata de existență a acesteia;",
              "n) gestionează situațiile excepționale și de criză;",
              "o) urmărește recuperarea eventualelor creanțe ale asociației;",
              "p) gestionează, conform hotărârilor adunării generale, derularea creditelor obținute pentru consolidare, reabilitare termică, creșterea calității ambiental-arhitecturale a condominiului și alte lucrări;",
              "q) propune sistemul propriu de penalizări ale asociației de proprietari pentru restanțele afișate pe lista de plată ce privesc cheltuielile asociației, în conformitate cu art. 77 din Legea nr. 196/2018 și a prevederilor legale în vigoare;",
              "r) notifică instituțiilor publice abilitate cazurile în care există suspiciuni de încălcare a prevederilor legale în vigoare;",
              "s) ține evidența și răspunde de păstrarea în bune condiții a arhivei documentelor financiar-contabile a asociației de proprietari;",
              "t) propune adunării generale cuantumul indemnizațiilor, precum și numărul și funcțiile personalului necesar a fi încadrat cu contract individual de muncă sau contract de prestări servicii în cadrul asociației de proprietari pentru buna administrare, gestionare și funcționare a condominiului, în limita bugetului de venituri și cheltuieli;",
              "u) exercită alte atribuții legale, care i-au fost conferite prin hotărârile adunării generale.",
            ],
            children: [
              {
                type: "paragraph",
                content: "(2) Comitetul executiv avizează toate documentele asociației de proprietari, corespondența și registrele privind gestiunea administratorului. (3) Ședințele comitetului executiv se țin cel puțin o dată pe lună și se convoacă pe bază de tabel convocator, de către președintele asociației de proprietari sau de către jumătate plus unu din numărul membrilor săi, cu cel puțin 5 zile înainte de data stabilită pentru ședință. (4) În situația extraordinară în care un membru al comitetului executiv se află în imposibilitatea de a-și exercita atribuțiile, în termen de cel mult 90 de zile de la data când s-a constatat indisponibilitatea acestuia se convoacă o adunare generală pentru alegerea unui nou membru al comitetului executiv.",
              },
            ],
          },
          {
            type: "article",
            id: "anexa1-art-25",
            title: "Articolul 25",
            content: "(1) Președintele asociației de proprietari este candidatul, membru al asociației de proprietari, ales prin voința sa și a jumătate plus unu din numărul proprietarilor prezenți în cadrul adunării generale. Președintele poate delega, pentru cel mult 90 de zile pe an, atribuțiile sale unui membru al comitetului executiv, fără a fi exonerat de răspundere juridică. (2) În caz de încetare a mandatului președintelui înainte de termen, comitetul executiv convoacă, în termen de 5 zile de la încetarea mandatului, o adunare generală pentru alegerea unui nou președinte. (3) În situația extraordinară în care în cadrul adunării generale nu este/nu poate fi ales un președinte, atribuțiile acestuia vor fi îndeplinite de către un membru al comitetului executiv ales prin decizie de către acesta conform prevederilor art. 55 din Legea nr. 196/2018, urmând ca în termen de cel mult 90 de zile de la data adunării generale să fie convocată o nouă adunare generală pentru alegerea unui nou președinte. (4) În situația extraordinară în care președintele se află în imposibilitatea de a-și exercita atribuțiile, atribuțiile acestuia vor fi îndeplinite de către un membru al comitetului executiv ales prin decizie de către acesta conform prevederilor art. 55 din Legea nr. 196/2018, urmând ca în termen de cel mult 90 de zile de la data când s-a constatat indisponibilitatea să fie convocată o adunare generală pentru a alege un nou președinte.",
          },
          {
            type: "article",
            id: "anexa1-art-26",
            title: "Articolul 26",
            content: "Președintele asociației de proprietari are următoarele atribuții:",
            items: [
              "a) în baza mandatului acordat de adunarea generală, reprezintă asociația de proprietari în relațiile cu terții, inclusiv în acțiunile în instanță;",
              "b) semnează documentele asociației de proprietari;",
              "c) supraveghează și urmărește corecta punere în aplicare a hotărârilor adunării generale, respectarea prevederilor statutului și acordului de asociere, precum și aplicarea deciziilor comitetului executiv;",
              "d) aduce la cunoștința proprietarilor prevederile statutului și regulamentului condominiului;",
              "e) răspunde în scris la sesizările și contestațiile scrise ale proprietarilor din condominiu în termen de maximum 10 zile de la primirea acestora;",
              "f) gestionează modul de îndeplinire a obligațiilor ce revin asociației de proprietari în raport cu autoritățile publice;",
              "g) prezintă spre verificare, la solicitarea organelor abilitate, toate documentele asociației, oferind toate informațiile solicitate;",
              "h) poate propune, în scris, comitetului executiv sau adunării generale, după caz, măsuri împotriva celor care nu respectă regulamentul condominiului, hotărârile și deciziile asociației de proprietari, conform prevederilor legale și statutare;",
              "i) întocmește și actualizează cartea de imobil, în conformitate cu legislația în vigoare;",
              "j) păstrează și asigură completarea la zi a cărții tehnice a construcției;",
              "k) asigură păstrarea documentelor privitoare la activitatea asociației de proprietari, conform legii;",
              "l) întocmește tabelul convocator și afișul pentru avizier pentru adunările generale și asigură semnarea acestuia de către proprietari;",
              "m) asigură informarea proprietarilor cu privire la ordinea de zi a adunărilor generale, cu 10 zile înainte de data stabilită pentru aceasta;",
              "n) afișează programul de încasări și datele de contact ale administratorului, ale membrilor comitetului executiv și ale membrilor comisiei de cenzori ori, după caz, ale cenzorului;",
              "o) afișează la avizier hotărârile adunării generale și ale ședințelor comitetului executiv în termen de maximum 7 zile de la data la care au avut loc acestea;",
              "p) în cazul modificării cadrului legislativ privind asociațiile de proprietari, președintele convoacă adunarea generală a asociației de proprietari pentru modificarea conformă a statutului asociației;",
              "q) informează proprietarii din condominiu cu privire la toate restricțiile referitoare la culoare, aspect, materiale și altele asemenea, stabilite prin regulamentul local de urbanism, conform informațiilor furnizate de autoritățile administrației publice locale;",
              "r) conduce ședințele adunărilor generale și ale comitetului executiv;",
              "s) afișează la avizier lista contractelor asociației de proprietari cu furnizorii de utilități publice, cu administratorul și cu personalul angajat sau contractual al asociației;",
              "t) afișează la avizier lista și datele de contact ale instituțiilor cu atribuții de inspecție și control la care pot fi sesizate eventualele nereguli legate de activitatea organelor de conducere ale asociației de proprietari, ale administratorului, respectiv ale membrilor asociației.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-27",
            title: "Articolul 27",
            content: "(1) Cenzorul/Comisia de cenzori sunt persoanele mandatate de asociația de proprietari să urmărească aplicarea prevederilor Legii nr. 196/2018 și ale statutului de către organele de conducere ale asociației de proprietari și să verifice execuția bugetului de venituri și cheltuieli conform prevederilor legale în vigoare. (2) Comisia de cenzori este formată dintr-un număr impar de membri, nu mai mare de cinci. (3) În cazul cenzorului persoană fizică, membru al asociației de proprietari, se vor avea în vedere prevederile art. 60 alin. (1) din Legea nr. 196/2018. (4) În cazul cenzorului persoană fizică, din afara asociației de proprietari, se vor avea în vedere prevederile art. 46 alin. (2) din Legea nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-28",
            title: "Articolul 28",
            content: "Cenzorul/Comisia de cenzori a asociației de proprietari are, în principal, următoarele atribuții:",
            items: [
              "a) urmărește aplicarea prevederilor Legii nr. 196/2018 și ale prezentului statut de către organele de conducere ale asociației de proprietari;",
              "b) verifică gestiunea financiar-contabilă;",
              "c) verifică lunar execuția bugetului de venituri și cheltuieli conform documentelor, registrelor și situației soldurilor elementelor de activ și pasiv întocmite de către administrator;",
              "d) cel puțin o dată pe an întocmește și prezintă adunării generale rapoarte asupra activității sale și asupra gestiunii asociației de proprietari, propunând măsuri;",
              "e) execută controale inopinate, împreună cu 2 membri ai comitetului executiv, pentru verificarea contabilității și a activității de casierie și consemnează rezultatele controalelor în registrul unic de procese-verbale al asociației de proprietari;",
              "f) participă la adunările generale ale asociației și ale comitetului executiv, asigurând legalitatea desfășurării acestora.",
            ],
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-7",
        title: "Capitolul VII - Administrarea condominiului",
        children: [
          {
            type: "article",
            id: "anexa1-art-29",
            title: "Articolul 29",
            content: "(1) Administrarea, exploatarea, întreținerea, repararea, reabilitarea și/sau modernizarea, după caz, a proprietății comune aferente condominiului sunt în sarcina asociației de proprietari, iar cheltuielile legate de aceste activități reprezintă cheltuieli comune. (2) În scopul administrării și întreținerii condominiului, asociația de proprietari încheie, conform art. 63-65 din Legea nr. 196/2018, contracte în numele proprietarilor cu persoane fizice, persoane fizice autorizate sau cu persoane juridice cu obiect de activitate administrarea condominiilor, înființate potrivit prevederilor legale în vigoare. (3) Desemnarea administratorului și încheierea contractului de administrare se fac de către comitetul executiv reprezentat de președintele asociației de proprietari, în baza mandatului acordat de adunarea generală, și decizia se comunică tuturor proprietarilor.",
          },
          {
            type: "article",
            id: "anexa1-art-30",
            title: "Articolul 30",
            content: "Administratorul are, în principal, următoarele atribuții:",
            items: [
              "a) administrează imobilul, propune și supraveghează lucrări având ca scop conservarea și întreținerea acestuia;",
              "b) supraveghează atât lucrările care privesc administrarea, cât și personalul angajat;",
              "c) în caz de urgență, cu acordul comitetului executiv, inițiază procedurile în vederea executării tuturor lucrărilor necesare protejării imobilului, cu respectarea legislației în vigoare;",
              "d) prestează serviciile prevăzute în contractul de administrare cu responsabilitate și în mod profesional;",
              "e) execută dispozițiile prevăzute în hotărârile adunării generale a asociației de proprietari, în conformitate cu Legea nr. 196/2018 și cu prezentul statut, cu regulamentul condominiului și conform contractului de administrare;",
              "f) organizează și conduce contabilitatea în partidă simplă și activitatea de casierie;",
              "g) gestionează, separat pentru fiecare asociație, bunurile materiale și fondurile bănești ale asociației, conform legislației în vigoare, hotărârilor adunării generale și deciziilor comitetului executiv;",
              "h) propune, cel târziu până la sfârșitul perioadei de recalculare a cheltuielilor, bugete anuale și prognoze pe termen mediu în care trebuie să includă sumele achitate, lucrările de întreținere și lucrările de reabilitare și îmbunătățire, sumele necesare din fondurile asociației, alte cheltuieli previzibile și o estimare generală a cheltuielilor asociației de proprietari;",
              "i) efectuează formalitățile necesare în angajarea contractelor cu furnizorii de servicii pentru exploatarea și întreținerea condominiului, derularea și urmărirea realizării acestor contracte;",
              "j) asigură gestionarea condominiului conform hotărârilor adunării generale și deciziilor comitetului executiv, cu respectarea prevederilor legale în vigoare;",
              "k) are obligația prezentării tuturor datelor, documentelor și informaților privind conținutul și respectarea contractului de administrare, precum și a acordurilor de plată în rate a cheltuielilor anuale, a cuantumului prestațiilor convenite, la solicitarea oricărui proprietar;",
              "l) gestionează, conform hotărârilor adunării generale sau comitetului executiv, fondul de rulment și fondul de reparații constituite la dispoziția asociației de proprietari, precum și alte fonduri constituite de către aceasta;",
              "m) calculează, întocmește, supune verificării cenzorilor/comisiei de cenzori, supune aprobării comitetului executiv și afișează la avizier lista lunară a cheltuielilor de întreținere, întocmită conform reglementărilor în vigoare, în termen de maximum 5 zile de la primirea ultimei facturi de la furnizorii de servicii;",
              "n) întocmește lunar și depune semestrial la compartimentul specializat în sprijinirea și îndrumarea asociațiilor de proprietari pe a cărei rază teritorială se află condominiul situația soldurilor elementelor de activ și pasiv;",
              "o) afișează lunar, la avizier, lista de venituri și cheltuieli ale asociației, care cuprinde inclusiv veniturile obținute din exploatarea proprietății comune;",
              "p) asigură, prin controale periodice, respectarea normelor generale de apărare împotriva incendiilor la utilizarea părților comune, funcționalitatea permanentă, la gabaritele proiectate, a căilor de evacuare în caz de incendiu și a celor de acces, intervenție și salvare și comunică de urgență președintelui asociației de proprietari/comitetului executiv neregulile identificate;",
              "q) îndeplinește orice alte atribuții stabilite în cadrul adunării generale a asociației de proprietari în conformitate cu Legea nr. 196/2018.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-31",
            title: "Articolul 31",
            content: "(1) Administratorul nu poate utiliza în niciun fel fondurile asociației de proprietari, fără hotărârea scrisă a adunării generale sau a deciziei comitetului executiv, după caz. (2) Administratorul are obligația de a ține evidențe contabile separate pentru fiecare condominiu în parte pe care îl are în administrare.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-8",
        title: "Capitolul VIII - Repartizarea cheltuielilor asociației de proprietari",
        children: [
          {
            type: "article",
            id: "anexa1-art-32",
            title: "Articolul 32",
            content: "(1) Repartizarea cheltuielilor pe număr de persoane care locuiesc sau desfășoară activități în proprietăți individuale se realizează conform art. 82 din Legea nr. 196/2018. (2) Repartizarea cheltuielilor pe consumuri individuale se realizează conform art. 83 din Legea nr. 196/2018. (3) Repartizarea cheltuielilor pe cota-parte indiviză de proprietate se realizează conform art. 84-86 din Legea nr. 196/2018. (4) Repartizarea cheltuielilor pe beneficiari se realizează conform art. 87-89 din Legea nr. 196/2018. (5) Repartizarea cheltuielilor pe consumatori tehnici se realizează conform art. 90 din Legea nr. 196/2018. (6) Repartizarea cheltuielilor de altă natură se realizează conform art. 91-93 din Legea nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-33",
            title: "Articolul 33",
            content: "Contractarea și facturarea serviciilor de utilități publice în condominii se realizează conform art. 94-101 din Legea nr. 196/2018.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-9",
        title: "Capitolul IX - Dizolvarea asociației de proprietari",
        children: [
          {
            type: "article",
            id: "anexa1-art-34",
            title: "Articolul 34",
            content: "În cazul în care numărul proprietarilor din condominiu scade sub 3 ca urmare a unor acte de înstrăinare, proprietarul sau proprietarii cer judecătoriei în a cărei circumscripție teritorială se află imobilul încetarea personalității juridice.",
          },
          {
            type: "article",
            id: "anexa1-art-35",
            title: "Articolul 35",
            content: "În cazul distrugerii în întregime sau parțială a condominiului, se aplică prevederile art. 657 din Legea nr. 287/2009 privind Codul civil, republicată, cu modificările ulterioare.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-10",
        title: "Capitolul X - Soluționarea litigiilor, relațiile contractuale, penalizările, cazurile de urgență",
        children: [
          {
            type: "article",
            id: "anexa1-art-36",
            title: "Articolul 36",
            content: "(1) În cazurile în care unul dintre proprietari împiedică, cu rea-credință și sub orice formă, folosirea normală a condominiului sau a unor părți componente, potrivit destinației acestora și creează prejudicii celorlalți proprietari, proprietarii prejudiciați sau orice persoană care se consideră vătămată într-un drept al său se poate adresa în scris președintelui, comitetului executiv al asociației de proprietari și instituțiilor cu atribuții privind respectarea ordinii și liniștii publice sau, după caz, instanțelor judecătorești. (2) Dacă o hotărâre a adunării generale a asociației de proprietari, o decizie a comitetului executiv sau a președintelui este contrară prevederilor Legii nr. 196/2018 sau este de natură să prejudicieze interesele proprietarilor, aceștia sau orice persoană care se consideră vătămată într-un drept al său poate sesiza cenzorul/comisia de cenzori, compartimentele prevăzute la art. 10 din Legea nr. 196/2018 sau, după caz, pot solicita instanțelor judecătorești anularea în tot sau în parte a hotărârii/deciziei și/sau repararea pagubei cauzate. (3) Orice persoană sau orice proprietar care se consideră vătămată/vătămat într-un drept al său din cauza neîndeplinirii sau îndeplinirii defectuoase a atribuțiilor de către președinte, membri ai comitetului executiv, cenzor/comisia de cenzori sau de către administrator se poate adresa în scris compartimentelor prevăzute la art. 10 din Legea nr. 196/2018 sau, după caz, instanțelor judecătorești.",
          },
          {
            type: "article",
            id: "anexa1-art-37",
            title: "Articolul 37",
            content: "(1) Dacă o hotărâre a adunării generale este contrară legii, prezentului statut sau acordului de asociere a asociației de proprietari ori este de natură să prejudicieze interesele proprietarilor, aceștia sau orice persoană care se consideră vătămată într-un drept al său pot/poate ataca în justiție respectiva hotărâre. (2) Acționarea în justiție în conformitate cu prevederile alin. (1) nu întrerupe executarea hotărârii decât în cazul în care instanța dispune suspendarea acesteia.",
          },
          {
            type: "article",
            id: "anexa1-art-38",
            title: "Articolul 38",
            content: "Cu un preaviz motivat scris de 5 zile emis de comitetul executiv al asociației de proprietari, proprietarul este obligat să permită accesul președintelui sau al unui membru al comitetului executiv, administratorului și al unei persoane calificate în realizarea lucrărilor de construcții/reparații, după caz, în proprietatea sa individuală, atunci când este necesar să se inspecteze, să se repare ori să se înlocuiască elemente din proprietatea comună, la care se poate avea acces numai din respectiva proprietate individuală. Fac excepție cazurile de urgență când termenul pentru preaviz este de 24 de ore.",
          },
          {
            type: "article",
            id: "anexa1-art-39",
            title: "Articolul 39",
            content: "În cazul în care proprietarul nu permite accesul în proprietatea sa, în conformitate cu prevederile art. 38, devin aplicabile prevederile art. 31 alin. (2) din Legea nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-40",
            title: "Articolul 40",
            content: "Asociația de proprietari, prin președinte, are dreptul de a acționa în instanță, conform prevederilor art. 78 din Legea nr. 196/2018, proprietarul care se face vinovat de neplata cotelor de contribuție la cheltuielile asociației mai mult de 60 de zile de la termenul scadent, respectiv 90 zile de la afișarea listei, informând membrii asociației prin afișare la avizier.",
          },
          {
            type: "article",
            id: "anexa1-art-41",
            title: "Articolul 41",
            content: "În imobilele de tip condominiu, facturarea serviciilor de utilități publice se face de către furnizor, cu respectarea prevederilor art. 94-101 din Legea nr. 196/2018, în unul dintre următoarele două moduri:",
            items: [
              "a) facturarea în comun la nivel de asociație de proprietari, reprezentând contravaloarea serviciului furnizat/prestat pentru întreg imobilul care se repartizează tuturor proprietarilor din condominiu, în conformitate cu regulile de repartizare stabilite prin Legea nr. 196/2018 și/sau prin legislația specifică serviciului de utilitate publică respectiv;",
              "b) facturarea individuală la nivel de proprietar, reprezentând contravaloarea serviciului furnizat/prestat pentru fiecare unitate de proprietate imobiliară din condominiu.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-42",
            title: "Articolul 42",
            content: "Facturarea individuală la nivel de proprietar în cadrul condominiului se face în baza:",
            items: [
              "a) convențiilor de facturare individuală, anexe la contractul de furnizare/prestare încheiat cu asociația de proprietari; sau",
              "b) contractului individual de furnizare/prestare a serviciilor încheiat cu fiecare proprietar.",
            ],
          },
          {
            type: "article",
            id: "anexa1-art-43",
            title: "Articolul 43",
            content: "(1) Furnizorul serviciilor de utilități publice are dreptul de a acționa în instanță proprietarul care se face vinovat de neplata facturilor individuale emise în baza contractelor individuale sau a convențiilor individuale, după caz, mai mult de 60 de zile de la termenul scadent, respectiv 90 de zile de la afișarea listei, cu notificarea proprietarului restant cu cel puțin 7 zile înainte de demararea procedurii de acțiune în instanță. (2) Sentința dată în favoarea furnizorului serviciilor de utilități publice, pentru sumele datorate, poate fi pusă în executare pentru acoperirea datoriilor la zi prin orice modalitate permisă de Legea nr. 134/2010 privind Codul de procedură civilă, republicată, cu modificările și completările ulterioare.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-11",
        title: "Capitolul XI - Asigurarea unui spațiu de administrare",
        children: [
          {
            type: "article",
            id: "anexa1-art-44",
            title: "Articolul 44",
            content: "Spațiul de administrare special amenajat în incinta condominiului în care se desfășoară serviciul de administrare: (se completează conform situației).",
          },
          {
            type: "article",
            id: "anexa1-art-45",
            title: "Articolul 45",
            content: "Spațiul special amenajat în incinta condominiului în care se desfășoară activitatea de casierie: (se completează conform situației).",
          },
          {
            type: "article",
            id: "anexa1-art-46",
            title: "Articolul 46",
            content: "Spațiul special amenajat în incinta condominiului în care se păstrează în siguranță documentele asociației: (se completează conform situației).",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa1-cap-12",
        title: "Capitolul XII - Dispoziții finale",
        children: [
          {
            type: "article",
            id: "anexa1-art-47",
            title: "Articolul 47",
            content: "Proprietarii comunică datele lor de contact (număr de telefon și adresă de e-mail) președintelui asociației de proprietari și administratorului, în vederea eficientizării comunicării între organele asociației de proprietari și proprietarii din condominiu, precum și pentru notificarea acestora cu celeritate în cazurile de urgență.",
          },
          {
            type: "article",
            id: "anexa1-art-48",
            title: "Articolul 48",
            content: "Hotărârile adunărilor generale se iau în cadrul adunării generale convocată sau reconvocată, după caz, în condițiile Legii nr. 196/2018.",
          },
          {
            type: "article",
            id: "anexa1-art-49",
            title: "Articolul 49",
            content: "(1) Pentru modificarea sau completarea prezentului statut ori a acordului de asociere, în cadrul adunării generale a asociației de proprietari este necesar acordul a cel puțin jumătate plus unu din numărul proprietarilor din condominiu. (2) Modificările și/sau completările aduse prezentului statut trebuie să fie motivate și aprobate prin hotărâre a adunării generale a asociației de proprietari într-o ședință convocată și desfășurată cu respectarea prevederilor prezentului statut și ale Legii nr. 196/2018. (3) Orice modificare sau completare a prezentului statut sau a acordului de asociere se înregistrează la judecătoria care a emis încheierea judecătorească de înființare, fără alte formalități. În acest sens, atât acordul de asociere, cât și statutul asociației de proprietari, actualizate, se depun de către președintele asociației de proprietari, ori de câte ori sunt modificări, la judecătoria în a cărei rază teritorială se află condominiul și care a emis încheierea judecătorească de înființare. (4) Modificările și/sau completările aduse prezentului statut sau acordului de asociere fără respectarea prevederilor alin. (3) nu sunt opozabile față de proprietarii care nu sunt membri ai asociației de proprietari sau față de terți.",
          },
        ],
      },
    ],
  },
  {
    type: "annexa",
    id: "anexa-2",
    title: "Anexa nr. 2 - CONȚINUT-CADRU al regulamentului condominiului",
    children: [
      {
        type: "paragraph",
        content: "Aprobat prin Ordinul nr. 1.058 din 11 februarie 2019, publicat în Monitorul Oficial, Partea I, nr. 149 din 25 februarie 2019.",
      },
      {
        type: "chapter",
        id: "anexa2-cap-1",
        title: "Capitolul I - Dispoziții generale",
        children: [
          {
            type: "article",
            id: "anexa2-art-1",
            title: "Articolul 1",
            content: "(1) Prezentul regulament de condominiu, denumit în continuare regulament, reprezintă documentul de ordine interioară al asociației de proprietari, care conține totalitatea instrucțiunilor, normelor, regulilor care stabilesc și asigură ordinea și buna funcționare a condominiului. (2) În aplicarea prezentului regulament, organele asociației de proprietari și proprietarii din condominiu vor ține cont de următoarele principii:",
            items: [
              "a) principiul egalității în drepturi și obligații, în condițiile legii, indiferent de statutul social;",
              "b) principiul tratamentului egal, al egalității între proprietari și al excluderii oricăror privilegii sau discriminări;",
              "c) principiul colaborării pentru apărarea drepturilor și a intereselor comune ce derivă din dreptul de proprietate comună indiviză;",
              "d) principiul asumării și respectării hotărârilor și deciziilor luate în cadrul organelor asociației de proprietari cu respectarea prevederilor legislației în vigoare, indiferent de opinia personală sau de modul în care au votat;",
              "e) principiul transparenței totale în ceea ce privește acțiunile sau inacțiunile care pot afecta dreptul de proprietate comună indiviză sau condominiul;",
              "f) principiul adoptării unei atitudini decente, corecte și civilizate în toate raporturile din cadrul asociației de proprietari și din cadrul condominiului;",
              "g) principiul respectului reciproc în interacțiunea dintre proprietarii din condominiu.",
            ],
          },
          {
            type: "article",
            id: "anexa2-art-2",
            title: "Articolul 2",
            content: "(1) Prezentul regulament conține regulile și condițiile de folosință a părților comune ale condominiului și normele de conduită și bună vecinătate dintre proprietari. (2) Dispozițiile prezentului regulament se completează cu dispozițiile Legii nr. 196/2018 privind înființarea, organizarea și funcționarea asociațiilor de proprietari și administrarea condominiilor. (3) Dispozițiile prezentului regulament sunt adoptate în conformitate cu prevederile legislației în vigoare și nu derogă de la acestea.",
          },
          {
            type: "article",
            id: "anexa2-art-3",
            title: "Articolul 3",
            content: "Prezentul regulament al condominiului a fost inițiat de (organul inițiator), a fost dezbătut și adoptat în adunarea generală a asociației de proprietari, cu acordul majorității proprietarilor din condominiu, în conformitate cu prevederile Legii nr. 196/2018, și va fi adus la cunoștință, prin afișare la avizier sau prin înmânarea unei copii conforme a acestuia, tuturor proprietarilor, în termen de 7 zile de la adoptare.",
          },
          {
            type: "article",
            id: "anexa2-art-4",
            title: "Articolul 4",
            content: "Regulamentul condominiului nu poate impune nicio restricție exercitării drepturilor proprietarilor în afara celor care sunt justificate prin destinația imobilului, așa cum este prevăzută în proiectul tehnic și cartea tehnică a construcției.",
          },
          {
            type: "article",
            id: "anexa2-art-5",
            title: "Articolul 5",
            content: "(1) Toți proprietarii, precum și chiriașii din condominiu, persoanele care locuiesc, persoanele care sunt găzduite pe perioadă determinată sau persoanele aflate în tranzit în condominiu sunt obligate să respecte prezentul regulament. (2) Responsabilitatea informării chiriașilor și a persoanelor care tranzitează condominiul referitor la prevederile regulamentului condominiului aparține proprietarului.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa2-cap-2",
        title: "Capitolul II - Folosința părților comune ale condominiului",
        children: [
          {
            type: "article",
            id: "anexa2-art-6",
            title: "Articolul 6",
            content: "Fiecare proprietar/locatar poate folosi, în condițiile legii și acordului de asociere, atât spațiul care constituie bunul principal, cât și părțile comune, fără a aduce atingere drepturilor celorlalți proprietari și fără a schimba destinația clădirii.",
          },
          {
            type: "article",
            id: "anexa2-art-7",
            title: "Articolul 7",
            content: "Fiecare proprietar/locatar poate exercita folosința bunurilor comune, cu condiția să respecte destinația acestuia și să permită exercitarea folosinței de către ceilalți proprietari în condiții normale.",
          },
          {
            type: "article",
            id: "anexa2-art-8",
            title: "Articolul 8",
            content: "(1) Proprietarii din condominiu au obligația de a menține și întreține curățenia proprietății comune, să protejeze și să mențină aspectul și integritatea clădirii. (2) Proprietarii din condominiu sunt obligați să respecte întocmai măsurile stabilite de autoritatea administrației publice locale pentru asigurarea igienei publice și salubrității, precum și regulile elementare de igienă în gospodăria sau locuința proprie, astfel încât să nu creeze disconfort vecinilor și să nu constituie pericol pentru sănătatea publică a comunității.",
          },
          {
            type: "article",
            id: "anexa2-art-9",
            title: "Articolul 9",
            content: "(1) Proprietarul este obligat să asigure întreținerea spațiului care constituie bunul principal, astfel încât clădirea să se păstreze în stare bună. (2) În cazul părților comune atribuite proprietarilor în folosință exclusivă, potrivit art. 43 din Legea nr. 196/2018, aceștia au obligația de a menține și întreține curățenia proprietății comune aflate în folosință exclusivă pe cheltuială proprie, fără realizarea de modificări constructive sau utilizarea în alte scopuri a acesteia.",
          },
          {
            type: "article",
            id: "anexa2-art-10",
            title: "Articolul 10",
            content: "Instalațiile comune se utilizează numai conform destinației acestora. Instalațiile și bunurile comune care necesită, conform legislației în vigoare, verificări periodice nu pot fi utilizate fără efectuarea reviziilor sau fără obținerea avizelor de funcționare.",
          },
          {
            type: "article",
            id: "anexa2-art-11",
            title: "Articolul 11",
            content: "(1) Este interzisă depozitarea oricăror obiecte pe proprietatea comună, dacă prin acest fapt se împiedică utilizarea normală a clădirii sau a părților comune sau dacă se aduce atingere drepturilor celorlalți proprietari. (2) Este interzisă abandonarea oricăror obiecte pe proprietatea comună.",
          },
          {
            type: "article",
            id: "anexa2-art-12",
            title: "Articolul 12",
            content: "Este interzisă blocarea sau obturarea căilor de acces în condominiu sau în proprietățile individuale.",
          },
          {
            type: "article",
            id: "anexa2-art-13",
            title: "Articolul 13",
            content: "Proprietarii din condominiu pot efectua, în cadrul proprietății individuale, lucrări de modificare și modernizare a proprietății, cu condiția ca acestea să nu contravină reglementărilor legale în vigoare, esteticii exterioare a imobilului/condominiu, proiectului inițial al imobilului, instalațiilor sanitare ale condominiului, să nu deterioreze sau să afecteze proprietățile individuale sau pe cele comune și să nu încalce drepturile de folosință ale celorlalți proprietari, conform proiectului clădirii.",
          },
          {
            type: "article",
            id: "anexa2-art-14",
            title: "Articolul 14",
            content: "Dacă proprietarul unei locuințe ori al unui spațiu cu altă destinație provoacă daune oricărei părți din proprietatea comună sau din proprietatea individuală a altui proprietar din condominiu, respectivul proprietar are obligația să repare stricăciunile sau să suporte cheltuielile pentru lucrările de reparații, în condițiile legii.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa2-cap-3",
        title: "Capitolul III - Norme de conduită și bună vecinătate dintre proprietari",
        children: [
          {
            type: "article",
            id: "anexa2-art-15",
            title: "Articolul 15",
            content: "Drepturile proprietarilor din condominiu nu pot fi lezate de nicio acțiune sau inacțiune a celorlalți proprietari din condominiu, de chiriași, persoanele care locuiesc, persoanele care sunt găzduite pe perioadă determinată sau persoanele aflate în tranzit în condominiu.",
          },
          {
            type: "article",
            id: "anexa2-art-16",
            title: "Articolul 16",
            content: "(1) Niciun proprietar nu poate, prin orice acțiune sau inacțiune, aduce atingere dreptului celorlalți proprietari din condominiu de acces la serviciile de utilități publice. (2) Proprietarii apartamentelor și ai spațiilor cu altă destinație decât aceea de locuință deconectați de la sistemul de alimentare centralizată cu energie termică al clădirii au obligația să își asigure o altă sursă de încălzire.",
          },
          {
            type: "article",
            id: "anexa2-art-17",
            title: "Articolul 17",
            content: "Este interzisă restricționarea accesului pe părțile comune a proprietarilor din condominiu, cu excepția cazurilor expres prevăzute de legislația în vigoare.",
          },
          {
            type: "article",
            id: "anexa2-art-18",
            title: "Articolul 18",
            content: "(1) Este interzisă introducerea și/sau depozitarea în cadrul condominiului a oricăror substanțe periculoase sau a substanțelor poluante, a deșeurilor, precum și a oricăror materiale și/sau bunuri care, prin natura lor sau printr-o greșită întrebuințare, pot conduce la apariția unor situații periculoase, punând astfel în pericol viața și siguranța proprietarilor/locatarilor sau integritatea clădirii. (2) Este interzisă depozitarea sau deversarea deșeurilor menajere în alte locuri decât cele special amenajate, conform legislației în vigoare.",
          },
          {
            type: "article",
            id: "anexa2-art-19",
            title: "Articolul 19",
            content: "(1) Este interzisă tulburarea, fără drept, a liniștii proprietarilor/locatarilor din condominiu prin producerea de zgomote cu orice aparat sau obiect ori prin strigăte sau larmă. (2) Este interzisă tulburarea liniștii proprietarilor/locatarilor din condominiu între orele 22,00-08,00, 13,00-14,00, conform Legii nr. 61/1991 pentru sancționarea faptelor de încălcare a unor norme de conviețuire socială, a ordinii și liniștii publice, republicată, de către orice persoană prin producerea de zgomote, larmă sau prin folosirea oricărui aparat, obiect ori instrument muzical la intensitate mare.",
          },
          {
            type: "article",
            id: "anexa2-art-20",
            title: "Articolul 20",
            content: "Proprietarii/Locatarii care dețin animale de companie au obligația să respecte prevederile legale pentru deținerea acestora, precum și obligația de a nu tulbura liniștea locatarilor, de a menține curățenia pe spațiile comune, precum și de a lua toate măsurile necesare pentru a nu aduce atingere drepturilor celorlalți proprietari.",
          },
        ],
      },
      {
        type: "chapter",
        id: "anexa2-cap-4",
        title: "Capitolul IV - Dispoziții finale",
        children: [
          {
            type: "article",
            id: "anexa2-art-21",
            title: "Articolul 21",
            content: "În cazul nerespectării regulamentului condominiului de către unul dintre proprietari sau chiriași, ceilalți proprietari pot sesiza președintele și/sau comitetul executiv al asociației de proprietari, cu privire la aceste nereguli.",
          },
          {
            type: "article",
            id: "anexa2-art-22",
            title: "Articolul 22",
            content: "În baza prezentului regulament nu sunt stabilite sau aplicate sancțiuni de către organele asociației de proprietari, iar încălcarea prevederilor prezentului regulament nu constituie contravenție.",
          },
          {
            type: "article",
            id: "anexa2-art-23",
            title: "Articolul 23",
            content: "Prezentul regulament se poate modifica/completa cu acordul majorității proprietarilor din condominiu și va fi adus la cunoștință, prin afișare la avizier sau prin înmânarea unei copii conforme a acestuia, tuturor proprietarilor, în termen de 7 zile de la adoptarea modificărilor/completărilor.",
          },
          {
            type: "article",
            id: "anexa2-art-24",
            title: "Articolul 24",
            content: "Prezentul regulament este adus la cunoștință tuturor proprietarilor din condominiu, prin afișare la avizier sau prin înmânarea unei copii conforme al acestuia, în termen de 7 zile de la adoptare.",
          },
          {
            type: "article",
            id: "anexa2-art-25",
            title: "Articolul 25",
            content: "Prezentul regulament intră în vigoare în termen de (se completează) zile de la adoptare, dar nu mai devreme de îndeplinirea obligației prevăzute la art. 24.",
          },
        ],
      },
      {
        type: "note",
        content: "Note privind completarea și aplicarea Regulamentului de condominiu: Se completează cu denumirea completă a asociației de proprietari, adresa completă, denumirea organului inițiator, data la care a fost dezbătut și adoptat în adunarea generală. Adunarea generală a asociației de proprietari poate adopta completări la Capitolul II (Folosința părților comune) și Capitolul III (Norme de conduită și bună vecinătate) cu acordul majorității proprietarilor din condominiu. Asociația de proprietari sau organele asociației de proprietari nu reprezintă agenți constatatori în sensul legislației în vigoare.",
      },
    ],
  },
];
